INSERT INTO RECRUITMENT (RECRUITMENT_NO, RECRUITMENT_TITLE, RECRUITMENT_CONTENT, RECRUITMENT_DEADLINE, 
JOBTYPE_NO, NUM_OF_RECRUITMENT_NAME, SALARY_NO, GRADE_NO, PERIOD_NO, DAYS_NO, TIME_NO, EMPLOYER_NO, 
SALARY_MOUNT, WRITE_DATE, RECRUITMENT_DEL_FL, MEMBER_NO, RECRUIT_COMPLETE_FL, WORKCOND_ADDRESS_TYPE_NO)
VALUES (SEQ_RECRUITMENT_NO.NEXTVAL, '가데이터65', '가데이터65', SYSDATE, 1, '1명', 1, 1, 1, 1, 1, 2, 2000000, 
SYSDATE, 'N', 18, 'N', '0101');

INSERT INTO RECRUITMENT_PREFERRED (RECRUITMENT_PREFERRED_NO, 
RECRUITMENT_NO, PREFERRED_NO) VALUES (SEQ_RECRUITMENT_PREFERRED_NO.NEXTVAL, 65, '01');
INSERT INTO RECRUITMENT_SUPPORT (RECRUITMENT_SUPPORT_NO, 
RECRUITMENT_NO, SUPPORT_NO) VALUES (SEQ_RECRUITMENT_SUPPORT_NO.NEXTVAL, 65, '0101');


