--컬럼 생성
ALTER TABLE PAYMENT_TYPE ADD PAYMENT_TYPE_DATE DATE NOT NULL;

--컬럼 순서 변경(숨겼다가 나오게 해서 순서변경)
ALTER TABLE PAYMENT_TYPE MODIFY PAYMENT_TYPE_REFUND_FL INVISIBLE;
ALTER TABLE PAYMENT_TYPE MODIFY PAYMENT_TYPE_REFUND_FL VISIBLE;

INSERT INTO "MEMBERSHIP" VALUES(
SEQ_MEMBERSHIP_NO.NEXTVAL, '플레티넘', '기본사용자 아무내용', 'N', SYSDATE, SYSDATE, SYSDATE,'N', 3);


INSERT INTO "EMPLOYER" VALUES(
SEQ_EMPLOYER_NO.NEXTVAL, '113-86-00917', '사람인', '서울특별시 구로구 디지털로34길 43, 14층(구로동, 코오롱싸이언스밸리1차)', NULL, 3, 19);


INSERT INTO "MEMBER" VALUES(
SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass01', '알바몬', '01022222222', SYSDATE, 'N', 1);


-- 시퀀스 번호 생성용
CREATE SEQUENCE SEQ_PAYMENT_TYPE_NO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999999999999999999999999999
       NOCYCLE
       NOCACHE
       NOORDER;

-- 각 번호 컬럼 pk 설정
ALTER TABLE PAYMENT_TYPE
ADD CONSTRAINT PK_PAYMENT_TYPE PRIMARY KEY (PAYMENT_TYPE_NO);

ALTER TABLE PAYMENT
ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_NO);

ALTER TABLE MEMBERSHIP
ADD CONSTRAINT PK_MEMBERSHIP PRIMARY KEY (MEMBERSHIP_NO);


CREATE TABLE PAYMENT_CROSS (
    PAYMENT_CROSS_NO NUMBER NOT NULL, -- PK 컬럼
    PAYMENT_TYPE_NO NUMBER NOT NULL, -- FK로 참조하는 컬럼
    PAYMENT_NO NUMBER NOT NULL, -- FK로 참조하는 컬럼

    -- PK 지정
    CONSTRAINT PK_PAYMENT_CROSS PRIMARY KEY (PAYMENT_CROSS_NO),

    -- PAYMENT_TYPE 테이블의 PAYMENT_TYPE_NO를 참조하는 FK 설정
    CONSTRAINT FK_PAYMENT_TYPE FOREIGN KEY (PAYMENT_TYPE_NO) 
    REFERENCES PAYMENT_TYPE (PAYMENT_TYPE_NO),

    -- PAYMENT 테이블의 PAYMENT_NO를 참조하는 FK 설정
    CONSTRAINT FK_PAYMENT FOREIGN KEY (PAYMENT_NO) 
    REFERENCES PAYMENT (PAYMENT_NO)
);

-- EMPLOYER 테이블의 EMPLOYER_NO를 참조하는 FK 추가
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_EMPLOYER_NO FOREIGN KEY (EMPLOYER_NO)
REFERENCES EMPLOYER (EMPLOYER_NO);

-- MEMBERSHIP 테이블의 MEMBERSHIP_NO를 참조하는 FK 추가
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_MEMBERSHIP_NO FOREIGN KEY (MEMBERSHIP_NO)
REFERENCES MEMBERSHIP (MEMBERSHIP_NO);

-- EMPLOYER 테이블의 EMPLOYER_NO를 참조하는 FK 추가
ALTER TABLE MEMBERSHIP
ADD CONSTRAINT FK_MEMBERSHIP_EMPLOYER FOREIGN KEY (EMPLOYER_NO)
REFERENCES EMPLOYER (EMPLOYER_NO);




