
--컬럼 생성
ALTER TABLE RESUME ADD RESUME_HIDE_FL CHAR(1) NULL;

ALTER TABLE PAYMENT_TYPE ADD CREATE_DATE DATE NULL;

--컬럼 순서 변경(숨겼다가 나오게 해서 순서변경)
ALTER TABLE WORKCOND_ADDRESS MODIFY RECRUITMENT_NO INVISIBLE;
ALTER TABLE WORKCOND_ADDRESS MODIFY RECRUITMENT_NO VISIBLE;

ALTER TABLE PAYMENT MODIFY EMPLOYER_NO INVISIBLE;
ALTER TABLE PAYMENT MODIFY EMPLOYER_NO VISIBLE;

--유니크 제약 조건
ALTER TABLE PAYMENT
ADD CONSTRAINT UQ_MERCHANT_UID UNIQUE (MERCHANT_UID);


CREATE TABLE PAYMENT_LOG (
    LOG_ID NUMBER PRIMARY KEY,                           -- 고유 식별자
    PAYMENT_NO NUMBER NOT NULL,                          -- 결제 번호
    STATUS VARCHAR2(50) NOT NULL,                        -- 결제 상태
    LOG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,        -- 로그 기록 시간
    DESCRIPTION VARCHAR2(255),                           -- 추가 설명
    MERCHANT_UID VARCHAR2(100) NOT NULL,                 -- 고유 결제 식별자
    CONSTRAINT FK_PAYMENT_NO FOREIGN KEY (PAYMENT_NO)    -- PAYMENT 테이블과 외래키 연계
        REFERENCES PAYMENT (PAYMENT_NO) ON DELETE CASCADE,
    CONSTRAINT UQ_PAYMENT_LOG_MERCHANT_UID UNIQUE (MERCHANT_UID)
);


--컬럼 삭제
alter table PAYMENT drop column PAYMENT_SECOND;

INSERT INTO "MEMBERSHIP" VALUES(
SEQ_MEMBERSHIP_NO.NEXTVAL, '플레티넘', '기본사용자 아무내용', 'N', SYSDATE, SYSDATE, SYSDATE,'N', 3);


INSERT INTO "EMPLOYER" VALUES(
SEQ_EMPLOYER_NO.NEXTVAL, '113-86-00917', '사람인', '서울특별시 구로구 디지털로34길 43, 14층(구로동, 코오롱싸이언스밸리1차)', NULL, 3, 19);


INSERT INTO "MEMBER" VALUES(
SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass01', '알바몬', '01022222222', SYSDATE, 'N', 1);


-- 시퀀스 번호 생성용
CREATE SEQUENCE SEQ_WORKCOND_ADDRESS_NO
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999999999999999999999999999
       NOCYCLE
       NOCACHE
       NOORDER;

-- 각 번호 컬럼 pk 설정
ALTER TABLE PAYMENT_TYPE
ADD CONSTRAINT PK_PAYMENT_TYPE PRIMARY KEY (PAYMENT_TYPE_NO);

ALTER TABLE PAYMENT
ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_NO);

ALTER TABLE MEMBERSHIP
ADD CONSTRAINT PK_MEMBERSHIP PRIMARY KEY (MEMBERSHIP_NO);


CREATE TABLE PAYMENT_CROSS (
    PAYMENT_CROSS_NO NUMBER NOT NULL, -- PK 컬럼
    PAYMENT_TYPE_NO NUMBER NOT NULL, -- FK로 참조하는 컬럼
    PAYMENT_NO NUMBER NOT NULL, -- FK로 참조하는 컬럼

    -- PK 지정
    CONSTRAINT PK_PAYMENT_CROSS PRIMARY KEY (PAYMENT_CROSS_NO),

    -- PAYMENT_TYPE 테이블의 PAYMENT_TYPE_NO를 참조하는 FK 설정
    CONSTRAINT FK_PAYMENT_TYPE FOREIGN KEY (PAYMENT_TYPE_NO) 
    REFERENCES PAYMENT_TYPE (PAYMENT_TYPE_NO),

    -- PAYMENT 테이블의 PAYMENT_NO를 참조하는 FK 설정
    CONSTRAINT FK_PAYMENT FOREIGN KEY (PAYMENT_NO) 
    REFERENCES PAYMENT (PAYMENT_NO)
);




-- EMPLOYER 테이블의 EMPLOYER_NO를 참조하는 FK 추가
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_EMPLOYER_NO FOREIGN KEY (EMPLOYER_NO)
REFERENCES EMPLOYER (EMPLOYER_NO);

-- MEMBERSHIP 테이블의 MEMBERSHIP_NO를 참조하는 FK 추가
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_MEMBERSHIP_NO FOREIGN KEY (MEMBERSHIP_NO)
REFERENCES MEMBERSHIP (MEMBERSHIP_NO);

-- EMPLOYER 테이블의 EMPLOYER_NO를 참조하는 FK 추가
ALTER TABLE MEMBERSHIP
ADD CONSTRAINT FK_MEMBERSHIP_EMPLOYER FOREIGN KEY (EMPLOYER_NO)
REFERENCES EMPLOYER (EMPLOYER_NO);


ALTER TABLE PAYMENT_TYPE
ADD PAYMENT_NO NUMBER;

ALTER TABLE PAYMENT_TYPE
ADD CONSTRAINT FK_PAYMENT_TYPE FOREIGN KEY (PAYMENT_NO)
REFERENCES PAYMENT (PAYMENT_NO);




CREATE TABLE WORKCOND_ADDRESS_RESUME (
    WORKCOND_ADDRESS_NO NUMBER PRIMARY KEY,  -- 고유 식별자 (PK)
    RECRUITMENT_NO NUMBER,                  -- 공고 번호 (FK)
    WORKCOND_ADDRESS_TYPE_NO NVARCHAR2(10), -- 주소 유형 번호 (FK)
    CONSTRAINT FK_RECRUITMENT_NO FOREIGN KEY (RECRUITMENT_NO)
        REFERENCES RECRUITMENT (RECRUITMENT_NO),
    CONSTRAINT FK_WORKCOND_ADDRESS_TYPE FOREIGN KEY (WORKCOND_ADDRESS_TYPE_NO)
        REFERENCES WORKCOND_ADDRESS_TYPE (WORKCOND_ADDRESS_TYPE_NO)
);

ALTER TABLE RESUME
ADD WORKCOND_ADDRESS_NO NUMBER;  -- 새로운 FK 컬럼 추가

ALTER TABLE RESUME
ADD CONSTRAINT FK_WORKCOND_ADDRESS_NO FOREIGN KEY (WORKCOND_ADDRESS_NO)
    REFERENCES WORKCOND_ADDRESS (WORKCOND_ADDRESS_NO);



CREATE TABLE WORKCOND_ADDRESS_TYPE (
    WORKCOND_ADDRESS_TYPE_NO NVARCHAR2(10) PRIMARY KEY, -- 주소번호 (기본 키)
    WORKCOND_ADDRESS_TYPE_INFO NVARCHAR2(100) NOT NULL                         		              
);


INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0106', '광진구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0107', '구로구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0108', '금천구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0109', '노원구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0110', '도봉구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0111', '동대문구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0112', '동작구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0113', '마포구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0114', '서대문구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0115', '서초구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0116', '성동구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0117', '성북구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0118', '송파구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0119', '양천구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0120', '영등포구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0121', '용산구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0122', '은평구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0123', '종로구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0124', '중구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0125', '중랑구');

-- 1단계: 인천광역시
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0200', '인천광역시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0201', '계양구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0202', '남동구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0203', '동구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0204', '미추홀구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0205', '부평구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0206', '서구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0207', '연수구');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0208', '중구');

-- 1단계: 경기도
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0300', '경기도');

-- 2단계: 경기도 산하 시·군 (가나다 순)
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0301', '가평군');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0302', '고양시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0303', '과천시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0304', '광명시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0305', '광주시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0306', '구리시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0307', '군포시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0308', '김포시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0309', '남양주시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0310', '동두천시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0311', '부천시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0312', '성남시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0313', '수원시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0314', '시흥시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0315', '안산시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0316', '안성시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0317', '안양시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0318', '양주시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0319', '양평군');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0320', '여주시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0321', '연천군');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0322', '오산시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0323', '용인시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0324', '의왕시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0325', '의정부시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0326', '이천시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0327', '파주시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0328', '평택시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0329', '포천시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0330', '하남시');
INSERT INTO "WORKCOND_ADDRESS_TYPE" VALUES('0331', '화성시');



COMMIT;


INSERT INTO "WORKCOND_ADDRESS" VALUES(41,3);


-- 1. 컬럼 추가
ALTER TABLE WORKCOND_ADDRESS
ADD RESUME_NO NUMBER;

-- 2. 외래 키 추가
ALTER TABLE WORKCOND_ADDRESS
ADD CONSTRAINT FK_WORKCOND_ADDRESS_RESUME
FOREIGN KEY (RESUME_NO)
REFERENCES RESUME (RESUME_NO)
ON DELETE CASCADE;


--3. 행삭제
DELETE FROM JOBTYPE
WHERE JOBTYPE_NO = 4;