-- 컬럼명 변경
ALTER TABLE RESUME RENAME COLUMN WORK_DATE_NO TO PERIOD_NO;
ALTER TABLE RESUME RENAME COLUMN PAY_TYPE TO SALARY_NO;
ALTER TABLE RESUME RENAME COLUMN INPUT_PAY TO SALARY_AMOUNT;

SELECT * FROM "RESUME";

-- 업직종 해소테이블
CREATE TABLE "RESUME_WORKTYPE" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"WORKTYPE_NO"	NVARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "RESUME_WORKTYPE"."RESUME_NO" IS '이력서번호(PFK)';
COMMENT ON COLUMN "RESUME_WORKTYPE"."WORKTYPE_NO" IS '업직종 번호(PFK)';

-- 복합키설정
ALTER TABLE "RESUME_WORKTYPE" ADD CONSTRAINT "PK_RESUME_WORKTYPE" PRIMARY KEY (
	"RESUME_NO",
	"WORKTYPE_NO"
);

ALTER TABLE "RESUME_WORKTYPE" ADD CONSTRAINT "FK_RESUME_TO_RESUME_WORKTYPE_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_WORKTYPE" ADD CONSTRAINT "FK_EMPLOYER_WORKTYPE_TO_RESUME_WORKTYPE_1" FOREIGN KEY (
	"WORKTYPE_NO"
)
REFERENCES "EMPLOYER_WORKTYPE" (
	"WORKTYPE_NO"
);


-- 희망근무조건_기간 해소테이블
CREATE TABLE "RESUME_PERIOD" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"PERIOD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_PERIOD"."RESUME_NO" IS '이력서번호(PFK)';
COMMENT ON COLUMN "RESUME_PERIOD"."PERIOD_NO" IS '근무기간 번호(PFK)';

-- 복합키설정
ALTER TABLE "RESUME_PERIOD" ADD CONSTRAINT "PK_RESUME_PERIOD" PRIMARY KEY (
	"RESUME_NO",
	"PERIOD_NO"
);

ALTER TABLE "RESUME_PERIOD" ADD CONSTRAINT "FK_RESUME_TO_RESUME_PERIOD_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_PERIOD" ADD CONSTRAINT "FK_WORKCOND_PERIOD_TO_RESUME_PERIOD_1" FOREIGN KEY (
	"PERIOD_NO"
)
REFERENCES "WORKCOND_PERIOD" (
	"PERIOD_NO"
);


-- 희망근무조건_요일 해소테이블


/*
 * DROP TABLE RESUME_DAYS;
CREATE TABLE "RESUME_DAYS" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"DAYS_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_DAYS"."RESUME_NO" IS '이력서번호(PFK)';
COMMENT ON COLUMN "RESUME_DAYS"."DAYS_NO" IS '근무요일 번호(PFK)';

-- 복합키설정
ALTER TABLE "RESUME_DAYS" ADD CONSTRAINT "PK_RESUME_DAYS" PRIMARY KEY (
	"RESUME_NO",
	"DAYS_NO"
);

ALTER TABLE "RESUME_DAYS" ADD CONSTRAINT "FK_RESUME_TO_RESUME_DAYS_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_DAYS" ADD CONSTRAINT "FK_WORKCOND_DAYS_TO_RESUME_DAYS_1" FOREIGN KEY (
	"DAYS_NO"
)
REFERENCES "WORKCOND_DAYS" (
	"DAYS_NO"
);


-- 희망근무조건_시간 해소테이블
DROP TABLE RESUME_TIME;
CREATE TABLE "RESUME_TIME" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"TIME_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_TIME"."RESUME_NO" IS '이력서번호(PFK)';
COMMENT ON COLUMN "RESUME_TIME"."TIME_NO" IS '근무시간 번호(PFK)';

-- 복합키설정
ALTER TABLE "RESUME_TIME" ADD CONSTRAINT "PK_RESUME_TIME" PRIMARY KEY (
	"RESUME_NO",
	"TIME_NO"
);

ALTER TABLE "RESUME_TIME" ADD CONSTRAINT "FK_RESUME_TO_RESUME_TIME_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_TIME" ADD CONSTRAINT "FK_WORKCOND_TIME_TO_RESUME_TIME_1" FOREIGN KEY (
	"TIME_NO"
)
REFERENCES "WORKCOND_TIME" (
	"TIME_NO"
);
*/

CREATE TABLE "RESUME_DAYSTIME" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"DAYS_NO"	NUMBER		NOT NULL,
	"TIME_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_DAYSTIME"."RESUME_NO" IS '이력서번호(PK)';
COMMENT ON COLUMN "RESUME_DAYSTIME"."DAYS_NO" IS '근무요일 번호(PK)';
COMMENT ON COLUMN "RESUME_DAYSTIME"."TIME_NO" IS '근무시간 번호(PK)';

ALTER TABLE "RESUME_DAYSTIME" ADD CONSTRAINT "PK_RESUME_DAYSTIME" PRIMARY KEY (
	"RESUME_NO",
	"DAYS_NO",
	"TIME_NO"
);

ALTER TABLE "RESUME_DAYSTIME" ADD CONSTRAINT "FK_RESUME_TO_RESUME_DAYSTIME_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_DAYSTIME" ADD CONSTRAINT "FK_WORKCOND_DAYS_TO_RESUME_DAYSTIME_1" FOREIGN KEY (
	"DAYS_NO"
)
REFERENCES "WORKCOND_DAYS" (
	"DAYS_NO"
);

ALTER TABLE "RESUME_DAYSTIME" ADD CONSTRAINT "FK_WORKCOND_TIME_TO_RESUME_DAYSTIME_1" FOREIGN KEY (
	"TIME_NO"
)
REFERENCES "WORKCOND_TIME" (
	"TIME_NO"
);

-----------------------------------------
-- 희망업직종 추가
INSERT INTO RESUME_WORKTYPE VALUES(1, '0100'); -- 외식
INSERT INTO RESUME_WORKTYPE VALUES(1, '0101'); -- 서빙
INSERT INTO RESUME_WORKTYPE VALUES(1, '0103'); -- 주방보조

COMMIT;

-------------------------
-- 희망근무기간 추가
INSERT INTO RESUME_PERIOD VALUES(1, 1); -- 무관
INSERT INTO RESUME_PERIOD VALUES(1, 8); -- 1년이상

-------------------------
-- 희망근무요일 추가
--INSERT INTO RESUME_DAYS VALUES(1, 5); -- 주말(토,일)
--INSERT INTO RESUME_DAYS VALUES(1, 10); -- 주2일

-------------------------
-- 희망근무시간 추가
--INSERT INTO RESUME_TIME VALUES(1, 4); -- 저녁 파트타임(18시~24시)
--INSERT INTO RESUME_TIME VALUES(1, 8); -- 저녁~새벽 파트타임

INSERT INTO RESUME_DAYSTIME VALUES(1, 5, 4);
INSERT INTO RESUME_DAYSTIME VALUES(1, 5, 8);
INSERT INTO RESUME_DAYSTIME VALUES(1, 10, 8);

SELECT * FROM "RESUME_DAYSTIME";

COMMIT;


---------------------------

-- 경력사항
CREATE TABLE "CAREER_INFO" (
	"CAREER_NO"	NUMBER		NOT NULL,
	"COMPANY_NAME"	NVARCHAR2(100)		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NULL,
	"CAREER_DESCRIPTION"	NVARCHAR2(500)		NULL,
	"WORKER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CAREER_INFO"."CAREER_NO" IS '경력사항고유식별번호(PK)';
COMMENT ON COLUMN "CAREER_INFO"."COMPANY_NAME" IS '회사명';
COMMENT ON COLUMN "CAREER_INFO"."START_DATE" IS '근무시작일';
COMMENT ON COLUMN "CAREER_INFO"."END_DATE" IS '근무종료일';
COMMENT ON COLUMN "CAREER_INFO"."CAREER_DESCRIPTION" IS '담당업무';
COMMENT ON COLUMN "CAREER_INFO"."WORKER_NO" IS '알바생번호(FK)';

-- 이력서경력사항(해소)
CREATE TABLE "RESUME_CAREER" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"CAREER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CAREER"."RESUME_NO" IS '이력서번호(PFK)';
COMMENT ON COLUMN "RESUME_CAREER"."CAREER_NO" IS '경력사항고유식별번호(PFK)';

ALTER TABLE "CAREER_INFO" ADD CONSTRAINT "PK_CAREER_INFO" PRIMARY KEY (
	"CAREER_NO"
);

ALTER TABLE "RESUME_CAREER" ADD CONSTRAINT "PK_RESUME_CAREER" PRIMARY KEY (
	"RESUME_NO",	
	"CAREER_NO"
);


ALTER TABLE "CAREER_INFO" ADD CONSTRAINT "FK_WORKER_TO_CAREER_INFO_1" FOREIGN KEY (
	"WORKER_NO"
)
REFERENCES "WORKER" (
	"WORKER_NO"
);

ALTER TABLE "RESUME_CAREER" ADD CONSTRAINT "FK_CAREER_INFO_TO_RESUME_CAREER_1" FOREIGN KEY (
	"CAREER_NO"
)
REFERENCES "CAREER_INFO" (
	"CAREER_NO"
);

ALTER TABLE "RESUME_CAREER" ADD CONSTRAINT "FK_RESUME_TO_RESUME_CAREER_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

COMMIT;

------------

CREATE SEQUENCE SEQ_CAREER_INFO_NO NOCACHE;

INSERT INTO CAREER_INFO VALUES(
	SEQ_CAREER_INFO_NO.NEXTVAL,
	'KH정보교육원',
	TO_DATE(20240101),
	TO_DATE(20241231),
	'풀스택강사',
	20
);

INSERT INTO CAREER_INFO VALUES(
	SEQ_CAREER_INFO_NO.NEXTVAL,
	'가나다상사',
	TO_DATE(20220101),
	TO_DATE(20231231),
	'회계,행정업무',
	20
);


COMMIT;


INSERT INTO RESUME_CAREER VALUES(1, 1);
INSERT INTO RESUME_CAREER VALUES(1, 2);


----------------------------------
-- 근무형태 해소테이블(JOBTYPE관련- 이미있음)
CREATE TABLE "RESUME_JOB_TYPE" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"JOBTYPE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_JOB_TYPE"."RESUME_NO" IS '이력서번호(PK)';
COMMENT ON COLUMN "RESUME_JOB_TYPE"."JOBTYPE_NO" IS '근무형태식별번호(PK)';

ALTER TABLE "RESUME_JOB_TYPE" ADD CONSTRAINT "PK_RESUME_JOB_TYPE" PRIMARY KEY (
	"RESUME_NO",
	"JOBTYPE_NO"
);

ALTER TABLE "RESUME_JOB_TYPE" ADD CONSTRAINT "FK_RESUME_TO_RESUME_JOB_TYPE_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_JOB_TYPE" ADD CONSTRAINT "FK_JOB_TYPE_TO_RESUME_JOB_TYPE_1" FOREIGN KEY (
	"JOBTYPE_NO"
)
REFERENCES "JOBTYPE" (
	"JOBTYPE_NO"
);

COMMIT;

INSERT INTO RESUME_JOB_TYPE VALUES(1, 1);
INSERT INTO RESUME_JOB_TYPE VALUES(1, 2);