SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 2
  AND B.MEMBERSHIP_DEL_FL = 'N';

 
	    SELECT 
	        A.EMPLOYER_NO AS EMPLOYER_NO,
	        B.MEMBERSHIP_NO AS MEMBERSHIP_NO,
	        B.MEMBERSHIP_TYPE AS MEMBERSHIP_TYPE,
	        B.MEMBERSHIP_START_DATE AS MEMBERSHIP_START_DATE,
	        B.MEMBERSHIP_END_DATE AS MEMBERSHIP_END_DATE,
	        B.MEMBERSHIP_EXPIRATION_DATE AS MEMBERSHIP_EXPIRATION_DATE,
	        (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) AS REMAINING_DAYS,
	        (SELECT C.MEMBERSHIP_NAME
	            FROM MEMBERSHIP_LEVEL C
	            WHERE C.MEMBERSHIP_NO = B.MEMBERSHIP_TYPE) AS MEMBERSHIP_NAME
	    FROM EMPLOYER A
	    JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
	    WHERE A.EMPLOYER_NO = 7
	    AND B.MEMBERSHIP_DEL_FL = 'N';

  
SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType,
    B.MEMBERSHIP_CONTENT AS membershipContent,
    (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) || '일' AS exp_Days
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 4
  AND B.MEMBERSHIP_DEL_FL = 'N';
 
 
SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType,
    B.MEMBERSHIP_CONTENT AS membershipContent,
    (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) || '일' AS exp_Days
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 2
  AND B.MEMBERSHIP_DEL_FL = 'N';


 
 INSERT INTO "MEMBERSHIP" VALUES(
SEQ_MEMBERSHIP_NO.NEXTVAL, 4, null, 'N', SYSDATE, SYSDATE, SYSDATE,'N', 2);

 INSERT INTO "MEMBERSHIP" VALUES(
SEQ_MEMBERSHIP_NO.NEXTVAL, 5, null, 'N', SYSDATE, SYSDATE, SYSDATE,'N', 3);


SELECT * FROM MEMBERSHIP_LEVEL;

SELECT * FROM MEMBERSHIP WHERE MEMBERSHIP_NO = 2;


SELECT * 
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK_MEMBERSHIP_NO';

SELECT * FROM MEMBERSHIP WHERE MEMBERSHIP_NO = 2;


	    SELECT 
	        A.EMPLOYER_NO AS EMPLOYER_NO,
	        B.MEMBERSHIP_NO AS MEMBERSHIP_NO,
	        B.MEMBERSHIP_TYPE AS MEMBERSHIP_TYPE,
	        B.MEMBERSHIP_START_DATE AS MEMBERSHIP_START_DATE,
	        B.MEMBERSHIP_END_DATE AS MEMBERSHIP_END_DATE,
	        (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) AS REMAINING_DAYS,
	        (SELECT C.MEMBERSHIP_NAME
	            FROM MEMBERSHIP_LEVEL C
	            WHERE C.MEMBERSHIP_NO = B.MEMBERSHIP_TYPE) AS MEMBERSHIP_NAME
	    FROM EMPLOYER A
	    JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
	    WHERE A.EMPLOYER_NO = #{employerNo}
	    AND B.MEMBERSHIP_DEL_FL = 'N';
	    
	    
	    
UPDATE MEMBERSHIP SET 
MEMBERSHIP_END_DATE = ADD_MONTHS(MEMBERSHIP_END_DATE, 1),
MEMBERSHIP_DEL_FL = 'N',
EMPLOYER_NO = 2
WHERE MEMBERSHIP_NO = 2
AND MEMBERSHIP_TYPE = 3;



SELECT * 
FROM MEMBERSHIP
WHERE EMPLOYER_NO =3;



SELECT * 
FROM MEMBERSHIP
WHERE MEMBERSHIP_DEL_FL ='N'
AND EMPLOYER_NO =2
AND (MEMBERSHIP_TYPE=2 OR MEMBERSHIP_TYPE=3);


DELETE FROM MEMBERSHIP
WHERE MEMBERSHIP_NO = 29;

DELETE FROM PAYMENT_TYPE
WHERE PAYMENT_TYPE_NO = 14;

COMMIT;


SELECT *
FROM (
    SELECT DISTINCT
        TO_CHAR(C.PAYMENT_DATE, 'YYYY-MM-DD HH24:MI:SS') AS PAYMENT_DATE,
        C.PAYMENT_NO AS PAYMENT_NO,
        C.PAYMENT_PRODUCT AS PAYMENT_PRODUCT,
        C.PAYMENT_AMOUNT AS PAYMENT_AMOUNT,
        C.PAYMENT_STATUS AS PAYMENT_STATUS,
        D.PAYMENT_TYPE_AMOUNT AS PAYMENT_TYPE_AMOUNT,
        D.PAYMENT_TYPE_PRODUCT AS PAYMENT_TYPE_PRODUCT,
        TO_CHAR(D.PAYMENT_TYPE_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS PAYMENT_TYPE_CREATE_DATE
    FROM 
        EMPLOYER E
    JOIN 
        MEMBERSHIP A ON E.EMPLOYER_NO = A.EMPLOYER_NO
    JOIN 
        PAYMENT_MEMBERSHIP B ON A.MEMBERSHIP_NO = B.MEMBERSHIP_NO
    JOIN 
        PAYMENT C ON B.PAYMENT_NO = C.PAYMENT_NO
    JOIN 
        PAYMENT_TYPE D ON C.PAYMENT_NO = D.PAYMENT_NO
    WHERE 
        E.EMPLOYER_NO = 3
) T
ORDER BY T.PAYMENT_DATE DESC;



	 SELECT 
    A.GRADE_NO AS GRADE_NO,
    A.MODIFICATION_DATE AS MODIFICATION_DATE,
    A.PERIOD_NO AS PERIOD_NO,
    A.REGISTRATION_DATE AS REGISTRATION_DATE,
    A.RESUME_CONTENT AS RESUME_CONTENT,
    A.RESUME_DEL_FL AS RESUME_DEL_FL,
    A.RESUME_DEL_FL AS RESUME_HIDE_FL,
    A.RESUME_NO AS RESUME_NO,
    A.RESUME_TITLE AS RESUME_TITLE,
    A.SALARY_AMOUNT AS SALARY_AMOUNT,
    A.SALARY_NO AS SALARY_NO,
    A.WORKCOND_ADDRESS_NO AS WORKCOND_ADDRESS_NO,
    A.WORKER_NO AS WORKER_NO,
    B.WORKCOND_ADDRESS_TYPE_NO AS WORKCOND_ADDRESS_TYPE_NO,
    C.WORKCOND_ADDRESS_TYPE_INFO AS WORKCOND_ADDRESS_TYPE_INFO,
    (
        SELECT 
            NVL(SUM(
                CASE 
                    WHEN CI.END_DATE IS NULL THEN TRUNC(SYSDATE) - TRUNC(CI.START_DATE)
                    ELSE TRUNC(CI.END_DATE) - TRUNC(CI.START_DATE)
                END
            ), 0)
        FROM 
            RESUME_CAREER RC
        JOIN 
            CAREER_INFO CI
        ON 
            RC.CAREER_NO = CI.CAREER_NO
        WHERE 
            RC.RESUME_NO = A.RESUME_NO
    ) AS TOTAL_CAREER
FROM 
    RESUME A
LEFT JOIN 
    WORKCOND_ADDRESS B
ON 
    A.WORKCOND_ADDRESS_NO = B.WORKCOND_ADDRESS_NO
LEFT JOIN 
    WORKCOND_ADDRESS_TYPE C
ON 
    B.WORKCOND_ADDRESS_TYPE_NO = C.WORKCOND_ADDRESS_TYPE_NO
WHERE 
    A.WORKER_NO = 9
    AND A.RESUME_DEL_FL = 'N'
ORDER BY 
    A.RESUME_NO DESC;




SELECT 
    R.WORKER_NO,
    R.RESUME_NO,
    SUM(
        CASE 
            WHEN CI.END_DATE IS NULL THEN TRUNC(SYSDATE) - TRUNC(CI.START_DATE) -- 종료일이 NULL인 경우 현재 날짜 사용
            ELSE TRUNC(CI.END_DATE) - TRUNC(CI.START_DATE) -- 종료일이 있는 경우 종료일 - 시작일 계산
        END
    ) AS TOTAL_DAYS
FROM 
    RESUME R
JOIN 
    RESUME_CAREER RC
    ON R.RESUME_NO = RC.RESUME_NO
JOIN 
    CAREER_INFO CI
    ON RC.CAREER_NO = CI.CAREER_NO
WHERE 
    R.WORKER_NO = 9
    AND R.RESUME_NO = 41
GROUP BY 
    R.WORKER_NO, R.RESUME_NO;




SELECT 
    A.GRADE_NO AS GRADE_NO,
    A.MODIFICATION_DATE AS MODIFICATION_DATE,
    A.PERIOD_NO AS PERIOD_NO,
    A.REGISTRATION_DATE AS REGISTRATION_DATE,
    A.RESUME_CONTENT AS RESUME_CONTENT,
    A.RESUME_DEL_FL AS RESUME_DEL_FL,
    A.RESUME_DEL_FL AS RESUME_HIDE_FL,
    A.RESUME_NO AS RESUME_NO,
    A.RESUME_TITLE AS RESUME_TITLE,
    A.SALARY_AMOUNT AS SALARY_AMOUNT,
    A.SALARY_NO AS SALARY_NO,
    A.WORKER_NO AS WORKER_NO,
    C.WORKCOND_ADDRESS_TYPE_NO AS WORKCOND_ADDRESS_TYPE_NO,
    C.WORKCOND_ADDRESS_TYPE_INFO AS WORKCOND_ADDRESS_TYPE_INFO,
    (
        SELECT 
            NVL(SUM(
                CASE 
                    WHEN D.END_DATE IS NULL THEN TRUNC(SYSDATE) - TRUNC(D.START_DATE)
                    ELSE TRUNC(D.END_DATE) - TRUNC(D.START_DATE)
                END
            ), 0)
        FROM 
            RESUME_CAREER RC
        JOIN 
            CAREER_INFO D
        ON 
            RC.CAREER_NO = D.CAREER_NO
        WHERE 
            RC.RESUME_NO = A.RESUME_NO
    ) AS TOTAL_CAREER
FROM 
    RESUME A
LEFT JOIN 
    WORKCOND_ADDRESS B
ON 
    A.RESUME_NO = B.RESUME_NO -- RESUME 테이블과 WORKCOND_ADDRESS 간의 연결
LEFT JOIN 
    WORKCOND_ADDRESS_TYPE C
ON 
    B.WORKCOND_ADDRESS_TYPE_NO = C.WORKCOND_ADDRESS_TYPE_NO -- WORKCOND_ADDRESS_TYPE와 조인
WHERE 
    A.WORKER_NO = 9
    AND A.RESUME_DEL_FL = 'N'
ORDER BY 
    A.RESUME_NO DESC;
   
   
   INSERT INTO WORKCOND_ADDRESS (
    WORKCOND_ADDRESS_NO,
    WORKCOND_ADDRESS_TYPE_NO,
    RESUME_NO
) VALUES (
    SEQ_WORKCOND_ADDRESS_NO.NEXTVAL, -- 자동 생성되는 시퀀스 값
    '0300',                          -- 추가할 주소 유형 번호
    27                               -- RECRUITMENT_NO = 16
);

   INSERT INTO WORKCOND_ADDRESS (
    WORKCOND_ADDRESS_NO,
    WORKCOND_ADDRESS_TYPE_NO,
    RECRUITMENT_NO
) VALUES (
    SEQ_WORKCOND_ADDRESS_NO.NEXTVAL, -- 자동 생성되는 시퀀스 값
    '0300',                          -- 추가할 주소 유형 번호
    12                               -- RECRUITMENT_NO = 16
);


SELECT DISTINCT
    A.RECRUITMENT_NO AS RECRUITMENT_NO,
    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
    A.RECRUITMENT_CONTENT AS RECRUITMENT_CONTENT,
    A.RECRUITMENT_DEADLINE AS RECRUITMENT_DEADLINE,
    A.NUM_OF_RECRUITMENT_NAME AS NUM_OF_RECRUITMENT_NAME,
    A.SALARY_NO AS SALARY_NO,
    A.GRADE_NO AS GRADE_NO,
    A.PERIOD_NO AS PERIOD_NO,
    A.DAYS_NO AS DAYS_NO,
    A.TIME_NO AS TIME_NO,
    A.EMPLOYER_NO AS EMPLOYER_NO,
    A.SALARY_MOUNT AS SALARY_MOUNT,
    A.WRITE_DATE AS WRITE_DATE,
    A.UPDATE_DATE AS UPDATE_DATE,
    A.RECRUITMENT_DEL_FL AS RECRUITMENT_DEL_FL,
    A.MEMBER_NO AS MEMBER_NO,
    A.RECRUIT_COMPLETE_FL AS RECRUIT_COMPLETE_FL,
    A.RECRUITMENT_PROFILE AS RECRUITMENT_PROFILE
FROM 
    WORKCOND_ADDRESS B
JOIN 
    WORKCOND_ADDRESS C
ON 
    B.WORKCOND_ADDRESS_TYPE_NO = C.WORKCOND_ADDRESS_TYPE_NO
JOIN 
    RECRUITMENT A
ON 
    C.RECRUITMENT_NO = A.RECRUITMENT_NO
WHERE 
    B.RESUME_NO = 41 -- 여긴 동적으로 받아와야함
    AND C.RECRUITMENT_NO IS NOT NULL
    OR (A.GRADE_NO = C.GRADE_NO);



   
   		        SELECT 
		            COUNT(DISTINCT B.RECRUITMENT_NO)
		        FROM 
		            WORKCOND_ADDRESS B
		        WHERE 
		            B.WORKCOND_ADDRESS_TYPE_NO IN (
		                SELECT DISTINCT F.WORKCOND_ADDRESS_TYPE_NO
		                FROM WORKCOND_ADDRESS F
		                WHERE F.RESUME_NO = A.RESUME_NO
		            )
		            AND B.RECRUITMENT_NO IS NOT NULL;

   SELECT DISTINCT
    A.RECRUITMENT_NO AS RECRUITMENT_NO,
    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
    A.RECRUITMENT_CONTENT AS RECRUITMENT_CONTENT,
    A.RECRUITMENT_DEADLINE AS RECRUITMENT_DEADLINE,
    A.NUM_OF_RECRUITMENT_NAME AS NUM_OF_RECRUITMENT_NAME,
    A.SALARY_NO AS SALARY_NO,
    A.GRADE_NO AS GRADE_NO,
    A.PERIOD_NO AS PERIOD_NO,
    A.DAYS_NO AS DAYS_NO,
    A.TIME_NO AS TIME_NO,
    A.EMPLOYER_NO AS EMPLOYER_NO,
    A.SALARY_MOUNT AS SALARY_MOUNT,
    A.WRITE_DATE AS WRITE_DATE,
    A.UPDATE_DATE AS UPDATE_DATE,
    A.RECRUITMENT_DEL_FL AS RECRUITMENT_DEL_FL,
    A.MEMBER_NO AS MEMBER_NO,
    A.RECRUIT_COMPLETE_FL AS RECRUIT_COMPLETE_FL,
    A.RECRUITMENT_PROFILE AS RECRUITMENT_PROFILE,
    G.GRADE_NAME AS GRADE_NAME -- 추가된 컬럼
FROM 
    RECRUITMENT A
LEFT JOIN 
    GRADE G
ON 
    A.GRADE_NO = G.GRADE_NO -- GRADE 테이블 조인
WHERE 
    EXISTS (
        SELECT 1 
        FROM WORKCOND_ADDRESS B
        JOIN WORKCOND_ADDRESS C
        ON B.WORKCOND_ADDRESS_TYPE_NO = C.WORKCOND_ADDRESS_TYPE_NO
        WHERE 
            B.RESUME_NO = 41 -- 동적으로 받아와야 함
            AND C.RECRUITMENT_NO = A.RECRUITMENT_NO
    )
    OR 
    A.GRADE_NO = (
        SELECT G.GRADE_NO
        FROM WORKCOND_ADDRESS B
        JOIN WORKCOND_ADDRESS C
        ON B.WORKCOND_ADDRESS_TYPE_NO = C.WORKCOND_ADDRESS_TYPE_NO
        WHERE 
            B.RESUME_NO = 41 -- 동적으로 받아와야 함
            AND C.RECRUITMENT_NO = A.RECRUITMENT_NO
    );
   
   
  SELECT DISTINCT
    A.RECRUITMENT_NO AS RECRUITMENT_NO,
    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
    A.RECRUITMENT_CONTENT AS RECRUITMENT_CONTENT,
    A.RECRUITMENT_DEADLINE AS RECRUITMENT_DEADLINE,
    A.NUM_OF_RECRUITMENT_NAME AS NUM_OF_RECRUITMENT_NAME,
    A.SALARY_NO AS SALARY_NO,
    A.GRADE_NO AS GRADE_NO,
    A.PERIOD_NO AS PERIOD_NO,
    A.DAYS_NO AS DAYS_NO,
    A.TIME_NO AS TIME_NO,
    A.EMPLOYER_NO AS EMPLOYER_NO,
    A.SALARY_MOUNT AS SALARY_MOUNT,
    A.WRITE_DATE AS WRITE_DATE,
    A.UPDATE_DATE AS UPDATE_DATE,
    A.RECRUITMENT_DEL_FL AS RECRUITMENT_DEL_FL,
    A.MEMBER_NO AS MEMBER_NO,
    A.RECRUIT_COMPLETE_FL AS RECRUIT_COMPLETE_FL,
    A.RECRUITMENT_PROFILE AS RECRUITMENT_PROFILE
FROM 
    RECRUITMENT A
JOIN 
    RESUME R
ON 
    A.GRADE_NO = R.GRADE_NO -- RECRUITMENT와 RESUME을 GRADE_NO로 조인
WHERE 
    A.RECRUITMENT_DEL_FL = 'N' -- 삭제되지 않은 공고만 조회
    AND R.RESUME_NO = 41; -- 동적으로 받아와야 함



SELECT B.GRADE_NAME AS GRADE_NAME
FROM RESUME A
JOIN GRADE B ON A.GRADE_NO = B.GRADE_NO
WHERE B.GRADE_NO = A.RESUME_NO;
    
  SELECT DISTINCT
    A.RECRUITMENT_NO AS RECRUITMENT_NO,
    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
    A.RECRUITMENT_CONTENT AS RECRUITMENT_CONTENT,
    A.RECRUITMENT_DEADLINE AS RECRUITMENT_DEADLINE,
    A.JOBTYPE_NO AS JOBTYPE_NO,
    A.NUM_OF_RECRUITMENT_NAME AS NUM_OF_RECRUITMENT_NAME,
    A.SALARY_NO AS SALARY_NO,
    A.GRADE_NO AS GRADE_NO,
    A.PERIOD_NO AS PERIOD_NO,
    A.DAYS_NO AS DAYS_NO,
    A.TIME_NO AS TIME_NO,
    A.EMPLOYER_NO AS EMPLOYER_NO,
    A.SALARY_MOUNT AS SALARY_MOUNT,
    A.WRITE_DATE AS WRITE_DATE,
    A.UPDATE_DATE AS UPDATE_DATE,
    A.RECRUITMENT_DEL_FL AS RECRUITMENT_DEL_FL,
    A.MEMBER_NO AS MEMBER_NO,
    A.RECRUIT_COMPLETE_FL AS RECRUIT_COMPLETE_FL,
    A.RECRUITMENT_PROFILE AS RECRUITMENT_PROFILE
FROM 
    RECRUITMENT A
WHERE 
    -- 삭제되지 않은 공고
    A.RECRUITMENT_DEL_FL = 'N'
    AND (
    
        -- 1.학력 조건
        A.GRADE_NO = (
            SELECT B.GRADE_NO
            FROM RESUME B
            WHERE B.RESUME_NO = 41)
            
        -- 2. 급여 조건 
        OR (
            A.SALARY_NO IN (1, 2) -- SALARY_NO가 1 또는 2일 때만 희망 금액 비교
            AND A.SALARY_NO = (
                SELECT B.SALARY_NO
                FROM RESUME B
                WHERE B.RESUME_NO = 41
            )
            AND A.SALARY_MOUNT >= (
                SELECT B.SALARY_AMOUNT
                FROM RESUME B
                WHERE B.RESUME_NO = 41
            )
        )
        
        OR A.SALARY_NO NOT IN (1, 2) -- SALARY_NO가 1, 2가 아닌 경우 SALARY_NO만 비교
        AND A.SALARY_NO = (
            SELECT B.SALARY_NO
            FROM RESUME B
            WHERE B.RESUME_NO = 41
        )
            
        -- 3.근무기간 조건
        OR
        A.PERIOD_NO = (
            SELECT B.PERIOD_NO
            FROM RESUME B
            WHERE B.RESUME_NO = 41)
            
        ----- 여기까진 단순비교 이후로는 1:다 ) --    
            
        -- 4.근무요일 조건
        OR
	        A.DAYS_NO IN (
	        SELECT E.DAYS_NO
	        FROM RESUME_DAYSTIME E
	        WHERE E.RESUME_NO = 41)
	        
	    -- 5.근무시간 조건
	    OR 
	    	A.TIME_NO IN (
	        SELECT E.TIME_NO
	        FROM RESUME_DAYSTIME E
	        WHERE E.RESUME_NO = 41)
	    
	    -- 6.근무형태 조건
	    OR 
	    	A.JOBTYPE_NO IN (
	        SELECT F.JOBTYPE_NO
	        FROM RESUME_JOB_TYPE F
	        WHERE F.RESUME_NO = 41)
	    
	        
        ----- 여기까진 1:다 이후로는 다:다) -- 	    
	        
	    -- 7.희망지역 조건
        OR
        A.RECRUITMENT_NO IN (
            SELECT DISTINCT D.RECRUITMENT_NO
            FROM WORKCOND_ADDRESS C
            JOIN WORKCOND_ADDRESS D
            ON C.WORKCOND_ADDRESS_TYPE_NO = D.WORKCOND_ADDRESS_TYPE_NO
            WHERE C.RESUME_NO = 41)
            
	    -- 8.업직종 조건    
        OR A.EMPLOYER_NO IN (
            SELECT DISTINCT G.EMPLOYER_NO
            FROM RESUME_WORKTYPE H
            JOIN BUSINESS_WORKTYPE G
            ON H.WORKTYPE_NO = G.WORKTYPE_NO
            WHERE H.RESUME_NO = 41
        )      
            
	)
   ORDER BY RECRUITMENT_NO DESC;

   


    



   SELECT COUNT(*) AS RECOMMENDATION
FROM 
    RECRUITMENT A
WHERE 
    -- 삭제되지 않은 공고
    A.RECRUITMENT_DEL_FL = 'N'
    AND (
    
        -- 1.학력 조건
        A.GRADE_NO = (
            SELECT B.GRADE_NO
            FROM RESUME B
            WHERE B.RESUME_NO = 41
        )
            
        -- 2. 급여 조건 
        OR (
            A.SALARY_NO IN (1, 2) -- SALARY_NO가 1 또는 2일 때만 희망 금액 비교
            AND A.SALARY_NO = (
                SELECT B.SALARY_NO
                FROM RESUME B
                WHERE B.RESUME_NO = 41
            )
            AND A.SALARY_MOUNT >= (
                SELECT B.SALARY_AMOUNT
                FROM RESUME B
                WHERE B.RESUME_NO = 41
            )
        )
        
        OR A.SALARY_NO NOT IN (1, 2) -- SALARY_NO가 1, 2가 아닌 경우 SALARY_NO만 비교
        AND A.SALARY_NO = (
            SELECT B.SALARY_NO
            FROM RESUME B
            WHERE B.RESUME_NO = 41
        )
            
        -- 3.근무기간 조건
        OR A.PERIOD_NO = (
            SELECT B.PERIOD_NO
            FROM RESUME B
            WHERE B.RESUME_NO = 41
        )
            
        ----- 여기까진 단순비교 이후로는 1:다 ) --    
            
        -- 4.근무요일 조건
        OR A.DAYS_NO IN (
            SELECT E.DAYS_NO
            FROM RESUME_DAYSTIME E
            WHERE E.RESUME_NO = 41
        )
	        
	    -- 5.근무시간 조건
	    OR A.TIME_NO IN (
	        SELECT E.TIME_NO
	        FROM RESUME_DAYSTIME E
	        WHERE E.RESUME_NO = 41
	    )
	    
	    -- 6.근무형태 조건
	    OR A.JOBTYPE_NO IN (
	        SELECT F.JOBTYPE_NO
	        FROM RESUME_JOB_TYPE F
	        WHERE F.RESUME_NO = 41
	    )
	        
	    ----- 여기까진 1:다 이후로는 다:다) -- 	    
	        
	    -- 7.희망지역 조건
        OR A.RECRUITMENT_NO IN (
            SELECT DISTINCT D.RECRUITMENT_NO
            FROM WORKCOND_ADDRESS C
            JOIN WORKCOND_ADDRESS D
            ON C.WORKCOND_ADDRESS_TYPE_NO = D.WORKCOND_ADDRESS_TYPE_NO
            WHERE C.RESUME_NO = 41
        )
            
	    -- 8.업직종 조건    
        OR A.EMPLOYER_NO IN (
            SELECT DISTINCT G.EMPLOYER_NO
            FROM RESUME_WORKTYPE H
            JOIN BUSINESS_WORKTYPE G
            ON H.WORKTYPE_NO = G.WORKTYPE_NO
            WHERE H.RESUME_NO = 41
        )      
            
	);


COMMIT;




SELECT 
    A.RESUME_CONTENT AS RESUME_CONTENT,
    A.RESUME_DEL_FL AS RESUME_DEL_FL,
    A.RESUME_HIDE_FL AS RESUME_HIDE_FL,
    A.RESUME_NO AS RESUME_NO,
    A.RESUME_TITLE AS RESUME_TITLE,
    D.GRADE_NAME AS GRADE_NAME, 
    A.PERIOD_NO AS PERIOD_NO,
    A.SALARY_AMOUNT AS SALARY_AMOUNT,
    A.SALARY_NO AS SALARY_NO,
    A.REGISTRATION_DATE AS REGISTRATION_DATE,
    A.MODIFICATION_DATE AS MODIFICATION_DATE,

    B.BLIND_LOGIN_ID AS BLIND_LOGIN_ID,
    B.FAST_LOGIN_TOKEN AS FAST_LOGIN_TOKEN,
    B.PROFILE_IMG AS PROFILE_IMG,
    B.SIGN_UP_PATH AS SIGN_UP_PATH,
    REGEXP_REPLACE(REGEXP_REPLACE(B.WORKER_ADDRESS, '^\d+\^\^\^', ''), '\^\^\^', '') AS WORKER_ADDRESS,
    TO_CHAR(B.WORKER_BIRTHDATE, 'YYYY') AS WORKER_BIRTHDATE,
    B.WORKER_BIRTHDATE,
    FLOOR(MONTHS_BETWEEN(TRUNC(SYSDATE), B.WORKER_BIRTHDATE) / 12) AS AGE,
    B.WORKER_ID AS WORKER_ID,
    B.WORKER_MBTI AS WORKER_MBTI,
    B.WORKER_NICKNAME AS WORKER_NICKNAME,
    B.WORKER_NO AS WORKER_NO,

    C.AUTHORITY_NO AS AUTHORITY_NO,
    C.ENROLL_DATE AS ENROLL_DATE,
    C.MEMBER_DEL_FL AS MEMBER_DEL_FL,
    C.MEMBER_EMAIL AS MEMBER_EMAIL,
    C.MEMBER_NAME AS MEMBER_NAME,
    C.MEMBER_NO AS MEMBER_NO,
    C.MEMBER_PW AS MEMBER_PW,
    SUBSTR(C.MEMBER_TEL, 1, 3) || '-' || 
    SUBSTR(C.MEMBER_TEL, 4, 4) || '-' || 
    SUBSTR(C.MEMBER_TEL, 8, 4) AS MEMBER_TEL
FROM 
    RESUME A
LEFT JOIN WORKER B ON A.WORKER_NO = B.WORKER_NO
LEFT JOIN MEMBER C ON B.MEMBER_NO = C.MEMBER_NO
LEFT JOIN GRADE D ON A.GRADE_NO = D.GRADE_NO 
WHERE 
    A.RESUME_NO = 41;
    
   
   
            SELECT DISTINCT D.RESUME_CAREER
            FROM WORKCOND_ADDRESS C
            JOIN WORKCOND_ADDRESS D
            ON C.WORKCOND_ADDRESS_TYPE_NO = D.WORKCOND_ADDRESS_TYPE_NO
            JOIN WORKCOND_ADDRESS D
            ON C.WORKCOND_ADDRESS_TYPE_NO = D.WORKCOND_ADDRESS_TYPE_NO
            WHERE C.RESUME_NO = 41;   
            
           
SELECT
    B.CAREER_NO,
    B.COMPANY_NAME,
    TO_CHAR(B.START_DATE, 'YYYY-MM-DD') AS START_DATE,
    B.START_DATE,
    B.END_DATE,
    B.CAREER_DESCRIPTION
FROM
    CAREER_INFO B
JOIN
    RESUME_CAREER A ON B.CAREER_NO = A.CAREER_NO
WHERE
    A.RESUME_NO = 41;



SELECT
	B.PERIOD_NO,
    B.PERIOD_NAME
FROM
    WORKCOND_PERIOD B
JOIN
    RESUME_PERIOD A ON B.PERIOD_NO  = A.PERIOD_NO
WHERE
    A.RESUME_NO = 41;
   
   
   
   
SELECT
	B.DAYS_NO,
    B.DAYS_NAME 
FROM
    WORKCOND_DAYS B
JOIN
    RESUME_DAYSTIME A ON B.DAYS_NO  = A.DAYS_NO
WHERE
    A.RESUME_NO = 41;
  
   

SELECT 
    B.SALARY_NAME
FROM RECRUITMENT A
JOIN SALARY B ON A.SALARY_NO  = B.SALARY_NO 
WHERE EMPLOYER_NO = A.RECRUITMENT_NO;


   
   
   
   
SELECT DISTINCT
		    A.RECRUITMENT_NO AS RECRUITMENT_NO,
		    REGEXP_SUBSTR(
		        SUBSTR(I.BUSINESS_ADDRESS, INSTR(I.BUSINESS_ADDRESS, '^^^') + 3, 
		        INSTR(I.BUSINESS_ADDRESS || '^^^', '^^^', INSTR(I.BUSINESS_ADDRESS, '^^^') + 3) - 
		        INSTR(I.BUSINESS_ADDRESS, '^^^') - 3),
		        '[^ ]+ [^ ]+', 1, 1
		    ) AS BUSINESS_ADDRESS,
		    I.BUSINESS_NAME AS BUSINESS_NAME,
		    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
		    A.RECRUITMENT_CONTENT AS RECRUITMENT_CONTENT,
		    A.RECRUITMENT_DEADLINE AS RECRUITMENT_DEADLINE,
		    A.JOBTYPE_NO AS JOBTYPE_NO,
		    A.NUM_OF_RECRUITMENT_NAME AS NUM_OF_RECRUITMENT_NAME,
		    A.SALARY_NO AS SALARY_NO,
		    J.SALARY_NAME AS SALARY_NAME,
		    K.TIME_NAME AS TIME_NAME,
		    A.GRADE_NO AS GRADE_NO,
		    A.PERIOD_NO AS PERIOD_NO,
		    A.DAYS_NO AS DAYS_NO,
		    A.TIME_NO AS TIME_NO,
		    A.EMPLOYER_NO AS EMPLOYER_NO,
		    A.SALARY_MOUNT AS SALARY_MOUNT,
		    A.WRITE_DATE AS WRITE_DATE,
		    A.UPDATE_DATE AS UPDATE_DATE,
		    A.RECRUITMENT_DEL_FL AS RECRUITMENT_DEL_FL,
		    A.MEMBER_NO AS MEMBER_NO,
		    A.RECRUIT_COMPLETE_FL AS RECRUIT_COMPLETE_FL,
		    A.RECRUITMENT_PROFILE AS RECRUITMENT_PROFILE,
		    A.WORKCOND_ADDRESS_TYPE_NO ASWORKCOND_ADDRESS_TYPE_NO
		FROM 
		    RECRUITMENT A
		JOIN 
			EMPLOYER I ON A.EMPLOYER_NO = I.EMPLOYER_NO
		JOIN	
			SALARY J ON A.SALARY_NO = J.SALARY_NO
		JOIN
			WORKCOND_TIME K ON A.TIME_NO = K.TIME_NO
		WHERE 
		    -- 삭제되지 않은 공고
		    A.RECRUITMENT_DEL_FL = 'N'
		    AND (
		    
		        -- 1.학력 조건
		        A.GRADE_NO = (
		            SELECT B.GRADE_NO
		            FROM RESUME B
		            WHERE B.RESUME_NO = 181)
		            
		        -- 2. 급여 조건 
		        OR (
		            A.SALARY_NO IN (1, 2) -- SALARY_NO가 1 또는 2일 때만 희망 금액 비교
		            AND A.SALARY_NO = (
		                SELECT B.SALARY_NO
		                FROM RESUME B
		                WHERE B.RESUME_NO = 181
		            )
		            AND A.SALARY_MOUNT >= (
		                SELECT B.SALARY_AMOUNT
		                FROM RESUME B
		                WHERE B.RESUME_NO = 181
		            )
		        )
		        
		        OR A.SALARY_NO NOT IN (1, 2) -- SALARY_NO가 1, 2가 아닌 경우 SALARY_NO만 비교
		        AND A.SALARY_NO = (
		            SELECT B.SALARY_NO
		            FROM RESUME B
		            WHERE B.RESUME_NO = 181
		        )
		            
		        -- 3.근무기간 조건
		        OR
		        A.PERIOD_NO = (
		            SELECT B.PERIOD_NO
		            FROM RESUME B
		            WHERE B.RESUME_NO = 181)
		            
		        -- 4.희망지역 조건    
		        OR
		        A.WORKCOND_ADDRESS_TYPE_NO = (
		            SELECT B.WORKCOND_ADDRESS_TYPE_NO
		            FROM WORKCOND_ADDRESS B
		            WHERE B.RESUME_NO = 181)
		            
		        ----- 여기까진 단순비교 이후로는 1:다 ) --    
		            
		        -- 4.근무요일 조건
		        OR
			        A.DAYS_NO IN (
			        SELECT E.DAYS_NO
			        FROM RESUME_DAYSTIME E
			        WHERE E.RESUME_NO = 181)
			        
			    -- 5.근무시간 조건
			    OR 
			    	A.TIME_NO IN (
			        SELECT E.TIME_NO
			        FROM RESUME_DAYSTIME E
			        WHERE E.RESUME_NO = 181)
			    
			    -- 6.근무형태 조건
			    OR 
			    	A.JOBTYPE_NO IN (
			        SELECT F.JOBTYPE_NO
			        FROM RESUME_JOB_TYPE F
			        WHERE F.RESUME_NO = 181)
			    
			        
		        ----- 여기까진 1:다 이후로는 다:다) -- 	    
			    
		            
			    -- 8.업직종 조건    
		        OR A.EMPLOYER_NO IN (
		            SELECT DISTINCT G.EMPLOYER_NO
		            FROM RESUME_WORKTYPE H
		            JOIN BUSINESS_WORKTYPE G
		            ON H.WORKTYPE_NO = G.WORKTYPE_NO
		            WHERE H.RESUME_NO = 181
		        )      
		            
			)
		   ORDER BY RECRUITMENT_NO DESC;
		   
		  
		  
		  
		
		SELECT DISTINCT A.RESUME_NO AS RESUME_NO
	    FROM RECRUITMENT_RESUME A
	    JOIN RECRUITMENT B ON A.RECRUITMENT_NO = B.RECRUITMENT_NO 
	    WHERE A.RESUME_NO = 41
	    AND B.EMPLOYER_NO = 4;
	    
	   
	SELECT 
    C.WORKCOND_ADDRESS_TYPE_INFO
FROM 
    RESUME A
JOIN 
    RESUME_ADDRESS B 
    ON A.RESUME_NO = B.RESUME_NO
JOIN 
    WORKCOND_ADDRESS_TYPE C 
    ON B.WORKCOND_ADDRESS_TYPE_NO = C.WORKCOND_ADDRESS_TYPE_NO
WHERE 
    A.RESUME_NO = #{resumeNo};

   
   INSERT INTO "RESUME_ADDRESS" VALUES(26,'0200');
	   
  
  

 SELECT COUNT(*)
FROM RECRUITMENT A
WHERE 
		    -- 삭제되지 않은 공고
		    A.RECRUITMENT_DEL_FL = 'N'
		    AND (
		    
		        -- 1.학력 조건
		        A.GRADE_NO = (
		            SELECT B.GRADE_NO
		            FROM RESUME B
		            WHERE B.RESUME_NO = 41)
		            
		        -- 2. 급여 조건 
		        OR (
		            A.SALARY_NO IN (1, 2) -- SALARY_NO가 1 또는 2일 때만 희망 금액 비교
		            AND A.SALARY_NO = (
		                SELECT B.SALARY_NO
		                FROM RESUME B
		                WHERE B.RESUME_NO = 41
		            )
		            AND A.SALARY_MOUNT >= (
		                SELECT B.SALARY_AMOUNT
		                FROM RESUME B
		                WHERE B.RESUME_NO = 41
		            )
		        )
		        
		        OR A.SALARY_NO NOT IN (1, 2) -- SALARY_NO가 1, 2가 아닌 경우 SALARY_NO만 비교
		        AND A.SALARY_NO = (
		            SELECT B.SALARY_NO
		            FROM RESUME B
		            WHERE B.RESUME_NO = 41
		        )
		            
		        -- 3.근무기간 조건
		        OR
		        A.PERIOD_NO = (
		            SELECT B.PERIOD_NO
		            FROM RESUME B
		            WHERE B.RESUME_NO = 41)

		        ----- 여기까진 단순비교 이후로는 1:다 ) --    
		        
		        -- 4.희망지역 조건    
		        OR
		        A.WORKCOND_ADDRESS_TYPE_NO IN (
		            SELECT B.WORKCOND_ADDRESS_TYPE_NO
		            FROM RESUME_ADDRESS B
		            WHERE B.RESUME_NO = 41)
		                
		        -- 5.근무요일 조건
		        OR
			        A.DAYS_NO IN (
			        SELECT E.DAYS_NO
			        FROM RESUME_DAYSTIME E
			        WHERE E.RESUME_NO = 41)
			        
			    -- 6.근무시간 조건
			    OR 
			    	A.TIME_NO IN (
			        SELECT E.TIME_NO
			        FROM RESUME_DAYSTIME E
			        WHERE E.RESUME_NO = 41)
			    
			    -- 7.근무형태 조건
			    OR 
			    	A.JOBTYPE_NO IN (
			        SELECT F.JOBTYPE_NO
			        FROM RESUME_JOB_TYPE F
			        WHERE F.RESUME_NO = 41)
			    
			        
		        ----- 여기까진 1:다 이후로는 다:다) -- 	    
			    
		            
			    -- 8.업직종 조건    
		        OR A.EMPLOYER_NO IN (
		            SELECT DISTINCT G.EMPLOYER_NO
		            FROM RESUME_WORKTYPE H
		            JOIN BUSINESS_WORKTYPE G
		            ON H.WORKTYPE_NO = G.WORKTYPE_NO
		            WHERE H.RESUME_NO = 41
		        )      
		            
			);
			

		
		SELECT 
    RECRUITMENT_NO, 
    RECRUITMENT_TITLE, 
    BUSINESS_NAME, 
    BUSINESS_ADDRESS, 
    SALARY_NAME, 
    SALARY_MOUNT, 
    TIME_NAME,
    CASE
        WHEN SYSDATE - WRITE_DATE < 1 / 24 / 60 THEN 
            FLOOR((SYSDATE - WRITE_DATE) * 24 * 60 * 60) || '초 전'
        WHEN SYSDATE - WRITE_DATE < 1 / 24 THEN 
            FLOOR((SYSDATE - WRITE_DATE) * 24 * 60) || '분 전'
        WHEN SYSDATE - WRITE_DATE < 1 THEN 
            FLOOR((SYSDATE - WRITE_DATE) * 24) || '시간 전'
        ELSE 
            TO_CHAR(WRITE_DATE, 'YYYY-MM-DD')
    END AS WRITE_DATE,
    TO_CHAR(RECRUITMENT_DEADLINE, 'YYYY/MM/DD') AS RECRUITMENT_DEADLINE
FROM 
    RECRUITMENT r
JOIN 
    EMPLOYER e ON r.EMPLOYER_NO = e.EMPLOYER_NO
JOIN 
    SALARY s ON r.SALARY_NO = s.SALARY_NO
JOIN 
    WORKCOND_TIME wt ON r.TIME_NO = wt.TIME_NO
WHERE 
    RECRUITMENT_DEL_FL = 'N'
ORDER BY 
    RECRUITMENT_NO DESC;

   
   		SELECT COUNT(*)
		FROM "RECRUITMENT"
		WHERE RECRUITMENT_DEL_FL = 'N';
		
		
		
		SELECT PERIOD_NO,PERIOD_NAME
		FROM WORKCOND_PERIOD
		ORDER BY 1;	
		
		
		
		
		
		
		
		
		
		
		SELECT DISTINCT
		    A.RECRUITMENT_NO AS RECRUITMENT_NO,
		    REGEXP_SUBSTR(
		        SUBSTR(I.BUSINESS_ADDRESS, INSTR(I.BUSINESS_ADDRESS, '^^^') + 3, 
		        INSTR(I.BUSINESS_ADDRESS || '^^^', '^^^', INSTR(I.BUSINESS_ADDRESS, '^^^') + 3) - 
		        INSTR(I.BUSINESS_ADDRESS, '^^^') - 3),
		        '[^ ]+ [^ ]+', 1, 1
		    ) AS BUSINESS_ADDRESS,
		    I.BUSINESS_NAME AS BUSINESS_NAME,
		    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
		    A.RECRUITMENT_CONTENT AS RECRUITMENT_CONTENT,
		    A.RECRUITMENT_DEADLINE AS RECRUITMENT_DEADLINE,
		    A.JOBTYPE_NO AS JOBTYPE_NO,
		    A.NUM_OF_RECRUITMENT_NAME AS NUM_OF_RECRUITMENT_NAME,
		    A.SALARY_NO AS SALARY_NO,
		    J.SALARY_NAME AS SALARY_NAME,
		    K.TIME_NAME AS TIME_NAME,
		    A.GRADE_NO AS GRADE_NO,
		    A.PERIOD_NO AS PERIOD_NO,
		    A.DAYS_NO AS DAYS_NO,
		    A.TIME_NO AS TIME_NO,
		    A.EMPLOYER_NO AS EMPLOYER_NO,
		    A.SALARY_MOUNT AS SALARY_MOUNT,
		    A.WRITE_DATE AS WRITE_DATE,
		    A.UPDATE_DATE AS UPDATE_DATE,
		    A.RECRUITMENT_DEL_FL AS RECRUITMENT_DEL_FL,
		    A.MEMBER_NO AS MEMBER_NO,
		    A.RECRUIT_COMPLETE_FL AS RECRUIT_COMPLETE_FL,
		    A.RECRUITMENT_PROFILE AS RECRUITMENT_PROFILE,
		    A.WORKCOND_ADDRESS_TYPE_NO ASWORKCOND_ADDRESS_TYPE_NO
		FROM 
		    RECRUITMENT A
		JOIN 
			EMPLOYER I ON A.EMPLOYER_NO = I.EMPLOYER_NO
		JOIN	
			SALARY J ON A.SALARY_NO = J.SALARY_NO
		JOIN
			WORKCOND_TIME K ON A.TIME_NO = K.TIME_NO
		WHERE 	
			A.RECRUITMENT_DEL_FL = 'N'
		AND A.RECRUITMENT_NO=16
		ORDER BY A.WRITE_DATE DESC;
		
	
SELECT *
FROM WORKCOND_ADDRESS_TYPE
WHERE WORKCOND_ADDRESS_TYPE_NO NOT LIKE '%00'
ORDER BY 1;

SELECT WORKTYPE_NO,WORKTYPE_CATEGORY
FROM EMPLOYER_WORKTYPE
WHERE WORKTYPE_CATEGORY LIKE '매장관리·판매'
ORDER BY 1;




SELECT DISTINCT
		    A.RECRUITMENT_NO AS RECRUITMENT_NO,
		    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
		    A.JOBTYPE_NO
		FROM 
		    RECRUITMENT A
		WHERE  A.RECRUITMENT_DEL_FL = 'N'
		AND (
		  	 A.JOBTYPE_NO IN (
		        SELECT B.JOBTYPE_NO
		        FROM JOBTYPE B
		        WHERE  B.JOBTYPE_NAME LIKE '알바'
			)
			
			)
		ORDER BY RECRUITMENT_NO DESC;
	
	
SELECT DISTINCT
    A.RECRUITMENT_NO AS RECRUITMENT_NO,
    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE
FROM 
    RECRUITMENT A
WHERE  
    A.RECRUITMENT_DEL_FL = 'N'
    AND A.RECRUITMENT_NO IN (
        SELECT DISTINCT B.RECRUITMENT_NO
        FROM RECRUITMENT_SUPPORT B
        JOIN SUPPORT C ON B.SUPPORT_NO = C.SUPPORT_NO
        WHERE C.SUPPORT_CATEGORY LIKE '퇴직금'
    )
ORDER BY 
    A.RECRUITMENT_NO DESC;

   
   SELECT DISTINCT
    A.RECRUITMENT_NO AS RECRUITMENT_NO,
    A.RECRUITMENT_TITLE AS RECRUITMENT_TITLE,
    A.WORKCOND_ADDRESS_TYPE_NO AS WORKCOND_ADDRESS_TYPE_NO
FROM 
    RECRUITMENT A
WHERE  
    A.RECRUITMENT_DEL_FL = 'N'
AND A.WORKCOND_ADDRESS_TYPE_NO LIKE '02%'
ORDER BY 
    RECRUITMENT_NO DESC;

