SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 2
  AND B.MEMBERSHIP_DEL_FL = 'N';

 
 SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType,
    B.MEMBERSHIP_CONTENT AS membershipContent
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 3
  AND B.MEMBERSHIP_DEL_FL = 'N';