SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 2
  AND B.MEMBERSHIP_DEL_FL = 'N';

 
	    SELECT 
	        A.EMPLOYER_NO AS EMPLOYER_NO,
	        B.MEMBERSHIP_NO AS MEMBERSHIP_NO,
	        B.MEMBERSHIP_TYPE AS MEMBERSHIP_TYPE,
	        B.MEMBERSHIP_START_DATE AS MEMBERSHIP_START_DATE,
	        B.MEMBERSHIP_END_DATE AS MEMBERSHIP_END_DATE,
	        B.MEMBERSHIP_EXPIRATION_DATE AS MEMBERSHIP_EXPIRATION_DATE,
	        (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) AS REMAINING_DAYS,
	        (SELECT C.MEMBERSHIP_NAME
	            FROM MEMBERSHIP_LEVEL C
	            WHERE C.MEMBERSHIP_NO = B.MEMBERSHIP_TYPE) AS MEMBERSHIP_NAME
	    FROM EMPLOYER A
	    JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
	    WHERE A.EMPLOYER_NO = 7
	    AND B.MEMBERSHIP_DEL_FL = 'N';

  
SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType,
    B.MEMBERSHIP_CONTENT AS membershipContent,
    (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) || '일' AS exp_Days
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 4
  AND B.MEMBERSHIP_DEL_FL = 'N';
 
 
SELECT 
    A.EMPLOYER_NO AS employerNo,
    B.MEMBERSHIP_TYPE AS membershipType,
    B.MEMBERSHIP_CONTENT AS membershipContent,
    (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) || '일' AS exp_Days
FROM EMPLOYER A
JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
WHERE A.EMPLOYER_NO = 2
  AND B.MEMBERSHIP_DEL_FL = 'N';


 
 INSERT INTO "MEMBERSHIP" VALUES(
SEQ_MEMBERSHIP_NO.NEXTVAL, 4, null, 'N', SYSDATE, SYSDATE, SYSDATE,'N', 2);

 INSERT INTO "MEMBERSHIP" VALUES(
SEQ_MEMBERSHIP_NO.NEXTVAL, 5, null, 'N', SYSDATE, SYSDATE, SYSDATE,'N', 3);


SELECT * FROM MEMBERSHIP_LEVEL;

SELECT * FROM MEMBERSHIP WHERE MEMBERSHIP_NO = 2;


SELECT * 
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'FK_MEMBERSHIP_NO';

SELECT * FROM MEMBERSHIP WHERE MEMBERSHIP_NO = 2;


	    SELECT 
	        A.EMPLOYER_NO AS EMPLOYER_NO,
	        B.MEMBERSHIP_NO AS MEMBERSHIP_NO,
	        B.MEMBERSHIP_TYPE AS MEMBERSHIP_TYPE,
	        B.MEMBERSHIP_START_DATE AS MEMBERSHIP_START_DATE,
	        B.MEMBERSHIP_END_DATE AS MEMBERSHIP_END_DATE,
	        (TRUNC(B.MEMBERSHIP_END_DATE) - TRUNC(B.MEMBERSHIP_START_DATE)) AS REMAINING_DAYS,
	        (SELECT C.MEMBERSHIP_NAME
	            FROM MEMBERSHIP_LEVEL C
	            WHERE C.MEMBERSHIP_NO = B.MEMBERSHIP_TYPE) AS MEMBERSHIP_NAME
	    FROM EMPLOYER A
	    JOIN MEMBERSHIP B ON A.EMPLOYER_NO = B.EMPLOYER_NO
	    WHERE A.EMPLOYER_NO = #{employerNo}
	    AND B.MEMBERSHIP_DEL_FL = 'N';
	    
	    
	    
UPDATE MEMBERSHIP SET 
MEMBERSHIP_END_DATE = ADD_MONTHS(MEMBERSHIP_END_DATE, 1),
MEMBERSHIP_DEL_FL = 'N',
EMPLOYER_NO = 2
WHERE MEMBERSHIP_NO = 2
AND MEMBERSHIP_TYPE = 3;



SELECT * 
FROM MEMBERSHIP
WHERE EMPLOYER_NO =3;



SELECT * 
FROM MEMBERSHIP
WHERE MEMBERSHIP_DEL_FL ='N'
AND EMPLOYER_NO =2
AND (MEMBERSHIP_TYPE=2 OR MEMBERSHIP_TYPE=3);


DELETE FROM MEMBERSHIP
WHERE MEMBERSHIP_NO = 29;

DELETE FROM PAYMENT_TYPE
WHERE PAYMENT_TYPE_NO = 14;

COMMIT;


SELECT *
FROM (
    SELECT DISTINCT
        TO_CHAR(C.PAYMENT_DATE, 'YYYY-MM-DD HH24:MI:SS') AS PAYMENT_DATE,
        C.PAYMENT_NO AS PAYMENT_NO,
        C.PAYMENT_PRODUCT AS PAYMENT_PRODUCT,
        C.PAYMENT_AMOUNT AS PAYMENT_AMOUNT,
        C.PAYMENT_STATUS AS PAYMENT_STATUS,
        D.PAYMENT_TYPE_AMOUNT AS PAYMENT_TYPE_AMOUNT,
        D.PAYMENT_TYPE_PRODUCT AS PAYMENT_TYPE_PRODUCT,
        TO_CHAR(D.PAYMENT_TYPE_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS PAYMENT_TYPE_CREATE_DATE
    FROM 
        EMPLOYER E
    JOIN 
        MEMBERSHIP A ON E.EMPLOYER_NO = A.EMPLOYER_NO
    JOIN 
        PAYMENT_MEMBERSHIP B ON A.MEMBERSHIP_NO = B.MEMBERSHIP_NO
    JOIN 
        PAYMENT C ON B.PAYMENT_NO = C.PAYMENT_NO
    JOIN 
        PAYMENT_TYPE D ON C.PAYMENT_NO = D.PAYMENT_NO
    WHERE 
        E.EMPLOYER_NO = 3
) T
ORDER BY T.PAYMENT_DATE DESC;




   




SELECT * FROM RESUME
WHERE WORKER_NO =9;