/* 이메일, 인증키 저장 테이블 생성 */
CREATE TABLE "AUTH_KEY"(
	"AUTH_KEY_NO"    NUMBER PRIMARY KEY,
	"EMAIL"	    NVARCHAR2(50) NOT NULL,
	"AUTH_KEY_CONTENT"  CHAR(6)	NOT NULL,
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO"      IS '인증키 구분 번호(시퀀스)';
COMMENT ON COLUMN "AUTH_KEY"."EMAIL"       IS '인증 이메일';
COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_CONTENT"    IS '인증 번호';
COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';

CREATE SEQUENCE SEQ_AUTH_KEY_NO NOCACHE; -- 인증키 구분 번호 시퀀스