-- 고용주 정보 집어넣기! (MEMBER TABLE에 넣고 나서 MEMBER_NO 갖고 EMPLOYER TABLE에 넣기)
-- 1) INSERT INTO 테이블명 VALUES(데이터, 데이터, 데이터, ...);
INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'testEmployer1@kh.or.kr','$2a$10$4a7QXSwo4aPsqYb5cJhO1.5EWFwozWdfC9PSas0mbC6nKbTeVTHAS', '테스트고용주1', '01098765432', SYSDATE, 'N', 1);
SELECT * FROM "MEMBER";

INSERT INTO "EMPLOYER" VALUES(SEQ_EMPLOYER_NO.NEXTVAL, '999-99-99999', '회사명1', '대분류^^^중분류^^^소분류', 1, 21);
SELECT * FROM "EMPLOYER";

COMMIT;


-- EMOLOYER LOGIN 시 SELECT 문
SELECT e.MEMBER_NO, EMPLOYER_NO, BUSINESS_REGISTRATION_NUMBER, BUSINESS_NAME, BUSINESS_ADDRESS,
	MEMBERSHIP_LEVEL, MEMBER_EMAIL, MEMBER_PW, MEMBER_NAME, MEMBER_TEL,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE,
	AUTHORITY
FROM "EMPLOYER" e
JOIN "MEMBER" m ON(e.MEMBER_NO = m.MEMBER_NO)
WHERE MEMBER_EMAIL = 'testEmployer1@kh.or.kr'
	AND MEMBER_DEL_FL = 'N';