SELECT e.EMPLOYER_NO, e.BUSINESS_REGISTRATION_NUMBER, e.BUSINESS_NAME, e.BUSINESS_ADDRESS, e.BUSINESS_NICKNAME,
	e.MEMBER_NO, m.MEMBER_EMAIL, m.MEMBER_NAME, m.MEMBER_TEL, ml.MEMBERSHIP_NAME 
FROM "EMPLOYER" e
JOIN "MEMBER" m ON(e.MEMBER_NO = m.MEMBER_NO)
JOIN "MEMBERSHIP_LEVEL" ml ON(e.MEMBERSHIP_LEVEL = ml.MEMBERSHIP_NO)
WHERE e.MEMBER_NO = 21;

SELECT * FROM EMPLOYER;
