-- ALTER TABLE 테이블명 DROP COLUMN 삭제할컬럼명;
ALTER TABLE EMPLOYER DROP COLUMN BUSINESS_IMG;

SELECT * FROM "EMPLOYER";
COMMIT;

----- 사업장 이미지 테이블 별도로 추가 + 코멘트 + 제약조건

CREATE TABLE "BUSINESS_IMG" (
	"BUSINESS_IMG_NO"	NUMBER		NOT NULL,
	"BUSINESS_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"BUSINESS_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"BUSINESS_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"BUSINESS_IMG_ORDER"	NUMBER		NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BUSINESS_IMG"."BUSINESS_IMG_NO" IS '이미지 번호(PK)';
COMMENT ON COLUMN "BUSINESS_IMG"."BUSINESS_IMG_PATH" IS '이미지 경로';
COMMENT ON COLUMN "BUSINESS_IMG"."BUSINESS_IMG_ORIGINAL_NAME" IS '이미지 원본명';
COMMENT ON COLUMN "BUSINESS_IMG"."BUSINESS_IMG_RENAME" IS '이미지 변경명';
COMMENT ON COLUMN "BUSINESS_IMG"."BUSINESS_IMG_ORDER" IS '이미지 순서';
COMMENT ON COLUMN "BUSINESS_IMG"."EMPLOYER_NO" IS '고용주번호(FK)';

ALTER TABLE "BUSINESS_IMG" ADD CONSTRAINT "PK_BUSINESS_IMG" PRIMARY KEY (
	"BUSINESS_IMG_NO"
);

ALTER TABLE "BUSINESS_IMG" ADD CONSTRAINT "FK_EMPLOYER_TO_BUSINESS_IMG_1" FOREIGN KEY (
	"EMPLOYER_NO"
)
REFERENCES "EMPLOYER" (
	"EMPLOYER_NO"
);

----------- EMPLOYER TABLE 에 컬럼 추가
-- ALTER TABLE 테이블명 ADD(컬럼명 데이터타입 [DEFAULT '값']);
ALTER TABLE "EMPLOYER" ADD(OPTIONAL_AGREE_FL CHAR(1) DEFAULT 'Y');
COMMENT ON COLUMN "EMPLOYER"."OPTIONAL_AGREE_FL" IS '공고추천, 멤버십 혜택 알람 동의 여부(Y/N)';
SELECT * FROM "EMPLOYER";
COMMIT;