SELECT e.EMPLOYER_NO, e.BUSINESS_REGISTRATION_NUMBER, e.BUSINESS_NAME, e.BUSINESS_ADDRESS, e.BUSINESS_NICKNAME,
	e.MEMBER_NO, m.MEMBER_EMAIL, m.MEMBER_NAME, m.MEMBER_TEL, ml.MEMBERSHIP_NAME 
FROM "EMPLOYER" e
JOIN "MEMBER" m ON(e.MEMBER_NO = m.MEMBER_NO)
JOIN "MEMBERSHIP_LEVEL" ml ON(e.MEMBERSHIP_LEVEL = ml.MEMBERSHIP_NO)
WHERE e.MEMBER_NO = 21;

SELECT * FROM "MEMBER";
SELECT * FROM "EMPLOYER";

SELECT e.MEMBER_NO, EMPLOYER_NO, 
	BUSINESS_REGISTRATION_NUMBER, BUSINESS_NAME, BUSINESS_ADDRESS, BUSINESS_NICKNAME,
	MEMBERSHIP_LEVEL, MEMBERSHIP_NAME,
	MEMBER_EMAIL, MEMBER_PW, MEMBER_NAME, MEMBER_TEL,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE,
	m.AUTHORITY_NO, AUTHORITY_NAME
FROM "EMPLOYER" e
JOIN "MEMBER" m ON(e.MEMBER_NO = m.MEMBER_NO)
JOIN MEMBERSHIP_LEVEL ml ON(e.MEMBERSHIP_LEVEL = ml.MEMBERSHIP_NO)
JOIN AUTHORITY a ON(m.AUTHORITY_NO = a.AUTHORITY_NO)
WHERE MEMBER_EMAIL = 'testEmployer1@kh.or.kr'
	AND m.AUTHORITY_NO = 1
	AND BUSINESS_NICKNAME = '본점'
	AND MEMBER_DEL_FL = 'N';

SELECT * FROM BUSINESS_WORKTYPE;

SELECT BUSINESS_WORKTYPE_NO, WORKTYPE_CATEGORY, EMPLOYER_NO 
FROM BUSINESS_WORKTYPE b
JOIN EMPLOYER_WORKTYPE ew ON (b.WORKTYPE_NO = ew.WORKTYPE_NO)
WHERE EMPLOYER_NO = 4;