-- 고용주 정보 집어넣기! (MEMBER TABLE에 넣고 나서 MEMBER_NO 갖고 EMPLOYER TABLE에 넣기)
-- 1) INSERT INTO 테이블명 VALUES(데이터, 데이터, 데이터, ...);
INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'testEmployer1@kh.or.kr','$2a$10$4a7QXSwo4aPsqYb5cJhO1.5EWFwozWdfC9PSas0mbC6nKbTeVTHAS', '테스트고용주1', '01098765432', SYSDATE, 'N', 1);
SELECT * FROM "MEMBER";

INSERT INTO "EMPLOYER" VALUES(SEQ_EMPLOYER_NO.NEXTVAL, '999-99-99999', '회사명1', '대분류^^^중분류^^^소분류', 1, 21);
SELECT * FROM "EMPLOYER";

COMMIT;


-- EMOLOYER LOGIN 시 SELECT 문
SELECT e.MEMBER_NO, EMPLOYER_NO, BUSINESS_REGISTRATION_NUMBER, BUSINESS_NAME, BUSINESS_ADDRESS,
	MEMBERSHIP_LEVEL, MEMBER_EMAIL, MEMBER_PW, MEMBER_NAME, MEMBER_TEL,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE,
	AUTHORITY_NO
FROM "EMPLOYER" e
JOIN "MEMBER" m ON(e.MEMBER_NO = m.MEMBER_NO)
WHERE MEMBER_EMAIL = 'testEmployer1@kh.or.kr'
	AND MEMBER_DEL_FL = 'N';
	
INSERT INTO "EMPLOYER" VALUES(SEQ_EMPLOYER_NO.NEXTVAL, '999-99-99999', '회사명1', '지점냈음-중분류-소분류', DEFAULT, 21, DEFAULT, '충남 천안점', '0412313213');

-- EMPLOYER_WORKTYPE PK 생성 및 컬럼 데이터 타입 변경, 데이터 삽입
SELECT * FROM "EMPLOYER_WORKTYPE";

ALTER TABLE "EMPLOYER_WORKTYPE" ADD CONSTRAINT "PK_WORKTYPE_NO" PRIMARY KEY (WORKTYPE_NO);
ALTER TABLE "EMPLOYER_WORKTYPE" MODIFY WORKTYPE_NO NVARCHAR2(10);

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0100', '외식·음료 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0101', '서빙');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0102', '주방장·조리사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0103', '주방보조·설거지');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0104', '바리스타');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0105', '제과제빵사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0106', '일반음식점');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0107', '레스토랑');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0108', '패밀리레스토랑');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0109', '패스트푸드점');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0110', '치킨·피자전문점');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0111', '커피전문점');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0112', '아이스크림·디저트');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0113', '베이커리·도넛·떡');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0114', '호프·일반주점');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0115', '바(bar)');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0116', '급식·푸드시스템');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0117', '도시락·반찬');

SELECT * FROM "EMPLOYER_WORKTYPE";
COMMIT;

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0200', '매장관리·판매 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0201', '매장관리·판매');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0202', '캐셔·카운터');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0203', '판촉도우미');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0204', 'MD·쇼핑몰운영');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0205', '백화점·쇼핑몰');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0206', '유통점·마트');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0207', '도소매·전통시장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0208', '편의점');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0209', '의류·잡화·쥬얼리매장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0210', '뷰티·헬스스토어');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0211', '휴대폰·전자기기매장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0212', '가구·침구·인테리어	');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0213', '생활용품샵');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0214', '서점·문구·팬시');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0215', '약국');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0216', '농수산·청과·축산');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0217', '화훼·꽃집');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0218', '스터디룸·독서실·고시원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0219', 'PC방');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0220', '노래방');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0221', '볼링·당구장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0222', '스크린 골프·야구');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0223', 'DVD·멀티방·만화카페');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0224', '오락실·게임장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0225', '이색테마카페');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0226', '키즈카페');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0227', '찜질방·사우나·스파');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0228', '피트니스·스포츠');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0229', '고속도로휴게소');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0230', '매장관리·판매 기타');

SELECT * FROM "EMPLOYER_WORKTYPE";
COMMIT;

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0300', '서비스 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0301', '놀이공원·테마파크');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0302', '호텔·리조트·숙박');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0303', '여행·캠프·레포츠');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0304', '영화관·공연장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0305', '전시·컨벤션·세미나');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0306', '안내데스크·리셉션');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0307', '주차유도·안내');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0308', '보안·경비·경호');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0309', '주유·세차');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0310', '렌터카·차량관리');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0311', '전단지배포');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0312', '청소·미화');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0313', '렌탈관리·A/S');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0314', '골프캐디');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0315', '헤어·미용·네일샵');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0316', '피부관리·마사지');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0317', '반려동물케어');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0318', '베이비시터·가사도우미');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0319', '결혼·연회·장례도우미');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0320', '이벤트·행사스텝');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0321', '나레이터모델');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0322', '피팅모델');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0323', '공인중개');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0324', '서비스 기타');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0400', '사무직 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0401', '사무보조');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0402', '문서작성·자료조사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0403', '데이터수집·가공');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0404', '비서');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0405', '경리·회계보조');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0406', '인사·총무');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0407', '마케팅·광고·홍보');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0408', '바이럴·SNS마케팅');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0409', '번역·통역');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0410', '복사·출력·제본');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0411', '편집·교정·교열');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0412', '공공기관·공기업·협회');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0413', '학교·도서관·교육기관');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0500', '고객상담·리서치·영업 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0501', '고객상담·인바운드');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0502', '텔레마케팅·아웃바운드');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0503', '쇼핑몰인바운드');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0504', '금융·보험영업');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0505', '오프라인영업·판매');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0506', '설문조사·리서치');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0507', '콜센터관리·모니터링');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0508', '영업관리·지원');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0600', '생산·건설·노무 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0601', '제조·가공·조립');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0602', '포장·품질검사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0603', '입출고·창고관리');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0604', '상하차·소화물 분류');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0605', '물류피킹·포장·전산');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0606', '지게차운전');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0607', '금형·사출·프레스·사상');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0608', '반도체·전자부품생산');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0609', '기계조작·오퍼레이터');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0610', '정비·수리·설치·A/S');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0611', '전기·시설물관리');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0612', '운반·설치·철거');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0613', '공사·건설현장');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0614', '전기·칸막이·배관공사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0615', '인테리어·보수공사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0616', '조선소');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0617', '재단·재봉');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0618', '생산·건설·노무 기타');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0700', 'IT·기술 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0701', '웹·콘텐츠기획');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0702', '사이트관리·기술지원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0703', '프로그래머');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0704', 'HTML코딩');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0705', 'QA·테스터·검증');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0706', '시스템·네트워크·보안');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0707', 'PC·디지털기기 설치·관리');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0800', '디자인 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0801', '웹·모바일디자인');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0802', '그래픽·영상·편집디자인');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0803', '제품·산업디자인');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0804', 'CAD·CAM·인테리어디자인');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0805', '캐릭터·애니메이션디자인');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0806', '패션·잡화디자인');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0807', '디자인 기타');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0900', '미디어 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0901', '보조출연·방청');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0902', '방송스텝·촬영보조');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0903', '동영상촬영·편집');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0904', '사진촬영·편집');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0905', '조명·음향');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0906', '방송사·프로덕션');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0907', '신문·잡지·출판');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('0908', '미디어 기타');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1000', '운전·배달 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1001', '화물·운송·이사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1002', '택배·배송기사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1003', '납품기사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1004', '중장비·특수차');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1005', '발렛파킹');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1006', '택시·대리·수행기사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1007', '버스·셔틀운전');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1008', '퀵서비스');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1009', '배달대행·음식배달');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1010', '도보배달');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1100', '병원·간호·연구 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1101', '간호조무사·간호사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1102', '의료기사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1103', '간병·요양보호사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1104', '원무·코디네이터');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1105', '외래보조·병동보조');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1106', '수의테크니션·동물보건사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1107', '실험·연구보조');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1108', '생동성·임상시험');

INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1200', '교육·강사 전체');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1201', '입시·보습학원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1202', '외국어·어학원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1203', '독서·논술·스피치학원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1204', '컴퓨터·정보통신');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1205', '요가·필라테스 강사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1206', '피트니스 트레이너');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1207', '레져스포츠 강사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1208', '예체능 강사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1209', '유아·유치원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1210', '등하원·승하차도우미');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1211', '방문·학습지');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1212', '보조교사');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1213', '자격증·기술학원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1214', '국비교육기관');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1215', '학원운영지원');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1216', '교재·교육콘텐츠제작');
INSERT INTO "EMPLOYER_WORKTYPE" VALUES('1217', '교육·강사 기타');

SELECT * FROM "EMPLOYER_WORKTYPE";
COMMIT;

-- BUSINESS_WORKTYPE PK 및 FK 생성, 데이터 타입 변경, 데이터 삽입
SELECT * FROM BUSINESS_WORKTYPE;

ALTER TABLE "BUSINESS_WORKTYPE" ADD CONSTRAINT "PK_BUSINESS_WORKTYPE_NO" PRIMARY KEY (BUSINESS_WORKTYPE_NO);
ALTER TABLE "BUSINESS_WORKTYPE" MODIFY WORKTYPE_NO NVARCHAR2(10);

ALTER TABLE "BUSINESS_WORKTYPE" ADD CONSTRAINT "FK_BW_EMPLOYER_NO" FOREIGN KEY ("EMPLOYER_NO")
REFERENCES "EMPLOYER" ("EMPLOYER_NO");

ALTER TABLE "BUSINESS_WORKTYPE" ADD CONSTRAINT "FK_BW_WORKTYPE_NO" FOREIGN KEY ("WORKTYPE_NO")
REFERENCES "EMPLOYER_WORKTYPE" ("WORKTYPE_NO");

CREATE SEQUENCE SEQ_BUSINESS_WORKTYPE_NO NOCACHE;

INSERT INTO "BUSINESS_WORKTYPE" VALUES (SEQ_BUSINESS_WORKTYPE_NO.NEXTVAL, 4, '0101');
INSERT INTO "BUSINESS_WORKTYPE" VALUES (SEQ_BUSINESS_WORKTYPE_NO.NEXTVAL, 4, '0104');
INSERT INTO "BUSINESS_WORKTYPE" VALUES (SEQ_BUSINESS_WORKTYPE_NO.NEXTVAL, 4, '0111');

INSERT INTO "BUSINESS_WORKTYPE" VALUES (SEQ_BUSINESS_WORKTYPE_NO.NEXTVAL, 6, '0201');
INSERT INTO "BUSINESS_WORKTYPE" VALUES (SEQ_BUSINESS_WORKTYPE_NO.NEXTVAL, 6, '0217');
INSERT INTO "BUSINESS_WORKTYPE" VALUES (SEQ_BUSINESS_WORKTYPE_NO.NEXTVAL, 6, '0225');

SELECT * FROM BUSINESS_WORKTYPE;
COMMIT;

-- delete 구문
DELETE FROM EMPLOYER
WHERE EMPLOYER_NO = 8;
COMMIT;

SELECT * FROM EMPLOYER;

-- SUPPORT TABLE PK 조건 추가
ALTER TABLE "SUPPORT" ADD CONSTRAINT "PK_SUPPORT_NO" PRIMARY KEY (SUPPORT_NO);
-- SUPPORT TABLE 에 데이터 삽입
INSERT INTO "SUPPORT" VALUES('0100', '보험');
SELECT * FROM SUPPORT;

INSERT INTO "SUPPORT" VALUES('0101', '국민연금');
INSERT INTO "SUPPORT" VALUES('0102', '고용보험');
INSERT INTO "SUPPORT" VALUES('0103', '산재보험');
INSERT INTO "SUPPORT" VALUES('0104', '건강보험');

INSERT INTO "SUPPORT" VALUES('0200', '휴무·휴가');
INSERT INTO "SUPPORT" VALUES('0201', '연차');
INSERT INTO "SUPPORT" VALUES('0202', '월차');
INSERT INTO "SUPPORT" VALUES('0203', '정기휴가');

INSERT INTO "SUPPORT" VALUES('0300', '보상제도');
INSERT INTO "SUPPORT" VALUES('0301', '인센티브제');
INSERT INTO "SUPPORT" VALUES('0302', '정기보너스');
INSERT INTO "SUPPORT" VALUES('0303', '퇴직금');
INSERT INTO "SUPPORT" VALUES('0304', '퇴직연금');
INSERT INTO "SUPPORT" VALUES('0305', '장기근속자 포상');
INSERT INTO "SUPPORT" VALUES('0306', '우수사원 표창/포상');

INSERT INTO "SUPPORT" VALUES('0400', '수당제도');
INSERT INTO "SUPPORT" VALUES('0401', '야간근로수당');
INSERT INTO "SUPPORT" VALUES('0402', '휴일근로수당');
INSERT INTO "SUPPORT" VALUES('0403', '연월차수당');
INSERT INTO "SUPPORT" VALUES('0404', '장기근속수당');
INSERT INTO "SUPPORT" VALUES('0405', '위험수당');
INSERT INTO "SUPPORT" VALUES('0406', '연장근로수당');

INSERT INTO "SUPPORT" VALUES('0500', '생활안정/경조사');
INSERT INTO "SUPPORT" VALUES('0501', '기숙사 운영');
INSERT INTO "SUPPORT" VALUES('0502', '명절 귀향비 지급');
INSERT INTO "SUPPORT" VALUES('0503', '각종 경조금');
INSERT INTO "SUPPORT" VALUES('0504', '경조휴가제');

INSERT INTO "SUPPORT" VALUES('0600', '생활편의');
INSERT INTO "SUPPORT" VALUES('0601', '조식 제공');
INSERT INTO "SUPPORT" VALUES('0602', '중식 제공');
INSERT INTO "SUPPORT" VALUES('0603', '석식 제공');
INSERT INTO "SUPPORT" VALUES('0604', '근무복 지급');
INSERT INTO "SUPPORT" VALUES('0605', '통근버스 운행');
INSERT INTO "SUPPORT" VALUES('0606', '야간교통비 지급');
INSERT INTO "SUPPORT" VALUES('0607', '차량유류보조금');
INSERT INTO "SUPPORT" VALUES('0608', '주차비 지원');
INSERT INTO "SUPPORT" VALUES('0609', '주차 가능');

SELECT * FROM SUPPORT;
COMMIT;



SELECT * FROM PREFERRED;
-- PREFERRED TABLE PK 조건 추가
ALTER TABLE "PREFERRED" ADD CONSTRAINT "PK_PREFERRED_NO" PRIMARY KEY (PREFERRED_NO);
-- PREFERRED TABLE 에 데이터 삽입
INSERT INTO "PREFERRED" VALUES('01', '영어가능');
INSERT INTO "PREFERRED" VALUES('02', '일본어 가능');
INSERT INTO "PREFERRED" VALUES('03', '중국어 가능');
INSERT INTO "PREFERRED" VALUES('04', '컴퓨터 활용 가능');
INSERT INTO "PREFERRED" VALUES('05', '포토샵 가능');
INSERT INTO "PREFERRED" VALUES('06', '한글(HWP) 가능');
INSERT INTO "PREFERRED" VALUES('07', '워드 가능');
INSERT INTO "PREFERRED" VALUES('08', '엑셀 가능');
INSERT INTO "PREFERRED" VALUES('09', '파워포인트 가능');
INSERT INTO "PREFERRED" VALUES('10', '차량소지');
INSERT INTO "PREFERRED" VALUES('11', '운전 가능');
INSERT INTO "PREFERRED" VALUES('12', '업무 관련 자격증 소지');
INSERT INTO "PREFERRED" VALUES('13', '유사업무 경험');
INSERT INTO "PREFERRED" VALUES('14', '인근 거주');
INSERT INTO "PREFERRED" VALUES('15', '대학 재학생');
INSERT INTO "PREFERRED" VALUES('16', '대학 휴학생');
