----- RECRUITMENT (채용공고) --------------------------------------------

CREATE TABLE "RECRUITMENT" (
	"RECRUITMENT_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_TITLE"	NVARCHAR2(100)		NOT NULL,
	"RECRUITMENT_CONTENT"	NVARCHAR2(2000)		NULL,
	"RECRUITMENT_DEADLINE"	DATE		NOT NULL,
	"WORKCOND_JOBTYPE"	NUMBER		NOT NULL,
	"NUM_OF_RECRUITMENT_NAME"	NVARCHAR2(20)		NOT NULL,
	"SALARY_NO"	NUMBER		NOT NULL,
	"GRADE_NO"	NUMBER		NOT NULL,
	"PERIOD_NO"	NUMBER		NOT NULL,
	"DAYS_NO"	NUMBER		NOT NULL,
	"TIME_NO"	NUMBER		NOT NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_NO" IS '공고번호(PK)';
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_TITLE" IS '채용공고 제목';
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_CONTENT" IS '채용공고 상세요강';
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_DEADLINE" IS 'ex) xxxx년xx월xx일';
COMMENT ON COLUMN "RECRUITMENT"."WORKCOND_JOBTYPE" IS '1(알바)/ 2(정규직)';
COMMENT ON COLUMN "RECRUITMENT"."NUM_OF_RECRUITMENT_NAME" IS '1(인원미정)/ 2(0명)/ 3(00명)';
COMMENT ON COLUMN "RECRUITMENT"."SALARY_NO" IS '급여조건 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."GRADE_NO" IS '학력번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."PERIOD_NO" IS '근무기간 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."DAYS_NO" IS '근무요일 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."TIME_NO" IS '근무시간 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."EMPLOYER_NO" IS '고용주 번호(FK)';

----- RECRUITMENT_SUPPORT (채용공고_복리후생) --------------------------------------------

CREATE TABLE "RECRUITMENT_SUPPORT" (
	"RECRUITMENT_SUPPORT_NO"	NUMBER		NOT NULL,
	"SUPPORT_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_SUPPORT"."RECRUITMENT_SUPPORT_NO" IS 'M:N 해소(PK)';
COMMENT ON COLUMN "RECRUITMENT_SUPPORT"."SUPPORT_NO" IS '복리후생 번호 (FK)';
COMMENT ON COLUMN "RECRUITMENT_SUPPORT"."RECRUITMENT_NO" IS '공고번호(FK)';

----- RECRUITMENT_PREFERRED (채용공고_우대사항) --------------------------------------------

CREATE TABLE "RECRUITMENT_PREFERRED" (
	"RECRUITMENT_PREFERRED_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL,
	"PREFERRED_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."RECRUITMENT_PREFERRED_NO" IS 'M:N 해소(PK)';
COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."RECRUITMENT_NO" IS '공고번호(FK)';
COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."PREFERRED_NO" IS '우대사항 번호(FK)';

----- RECRUITMENT_IMG (공고 이미지) --------------------------------------------

CREATE TABLE "RECRUITMENT_IMG" (
	"RECRUITMENT_IMG_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_IMG_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"RECRUITMENT_IMG_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUITMENT_IMG_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUITMENT_IMG_IMG_ORDER"	NUMBER		NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_NO" IS '이미지 번호(PK)';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_PATH" IS '이미지 경로';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_ORIGINAL_NAME" IS '이미지 원본명';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_RENAME" IS '이미지 변경명';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_ORDER" IS '이미지 순서';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_NO" IS '공고번호(FK)';

----- GRADE (학력) --------------------------------------------

CREATE TABLE "GRADE" (
	"GRADE_NO"	NUMBER		NOT NULL,
	"GRADE_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_NO" IS '학력번호(PK)';
COMMENT ON COLUMN "GRADE"."GRADE_NAME" IS 'ex) 무관, 중졸, 고졸, 대졸, 석사 이상';

----- WORKCOND_PERIOD (근무기간) --------------------------------------------

CREATE TABLE "WORKCOND_PERIOD" (
	"PERIOD_NO"	NUMBER		NOT NULL,
	"PERIOD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_PERIOD"."PERIOD_NO" IS '근무기간 번호(PK)';
COMMENT ON COLUMN "WORKCOND_PERIOD"."PERIOD_NAME" IS 'ex) 하루, 1주일 이하, 1주일~1개월';

----- WORKCOND_DAYS (근무요일) --------------------------------------------

CREATE TABLE "WORKCOND_DAYS" (
	"DAYS_NO"	NUMBER		NOT NULL,
	"DATS_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_DAYS"."DAYS_NO" IS '근무요일 번호(PK)';
COMMENT ON COLUMN "WORKCOND_DAYS"."DATS_NAME" IS 'ex) 월~일, 월~토, 주말(토, 일), 주5일';

----- WORKCOND_TIME (근무시간) --------------------------------------------

CREATE TABLE "WORKCOND_TIME" (
	"TIME_NO"	NUMBER		NOT NULL,
	"TIME_NAME"	NVARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_TIME"."TIME_NO" IS '근무시간 번호(PK)';
COMMENT ON COLUMN "WORKCOND_TIME"."TIME_NAME" IS 'ex) 오전, 오후. 오전~오후, 새벽~오전';

----- RECRUITMENT_SALARY (급여) --------------------------------------------

CREATE TABLE "RECRUITMENT_SALARY" (
	"SALARY_NO"	NUMBER		NOT NULL,
	"SALARY_NAME"	NUMBER		NOT NULL,
	"SALARY_MOUNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_SALARY"."SALARY_NO" IS '급여조건 번호(PK)';
COMMENT ON COLUMN "RECRUITMENT_SALARY"."SALARY_NAME" IS '1(시급)/ 2(월급)/ 3(추후협의)';
COMMENT ON COLUMN "RECRUITMENT_SALARY"."SALARY_MOUNT" IS 'ex) 10,300(시급)/ 3,000,000(월급)';


COMMIT;


----- PK --------------------------------------------
ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "PK_RECRUITMENT_NO" PRIMARY KEY ("RECRUITMENT_NO");

ALTER TABLE "RECRUITMENT_SUPPORT" ADD CONSTRAINT "PK_RECRUITMENT_SUPPORT_NO" PRIMARY KEY ("RECRUITMENT_SUPPORT_NO");

ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "PK_RECRUITMENT_PREFERRED_NO" PRIMARY KEY ("RECRUITMENT_PREFERRED_NO");

ALTER TABLE "RECRUITMENT_IMG" ADD CONSTRAINT "PK_RECRUITMENT_IMG_NO" PRIMARY KEY ("RECRUITMENT_IMG_NO");

ALTER TABLE "GRADE" ADD CONSTRAINT "PK_GRADE_NO" PRIMARY KEY ("GRADE_NO");

ALTER TABLE "WORKCOND_PERIOD" ADD CONSTRAINT "PK_WORKCOND_PERIOD_NO" PRIMARY KEY ("PERIOD_NO");

ALTER TABLE "WORKCOND_DAYS" ADD CONSTRAINT "PK_WORKCOND_DAYS_NO" PRIMARY KEY ("DAYS_NO");

ALTER TABLE "WORKCOND_TIME" ADD CONSTRAINT "PK_WORKCOND_TIME_NO" PRIMARY KEY ("TIME_NO");

ALTER TABLE "RECRUITMENT_SALARY" ADD CONSTRAINT "PK_RECRUITMENT_SALARY_NO" PRIMARY KEY ("SALARY_NO");


----- FK --------------------------------------------

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_RECRUITMENT_SALARY_TO_RECRUITMENT_1" FOREIGN KEY ("SALARY_NO")
REFERENCES "RECRUITMENT_SALARY" ("SALARY_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_GRADE_TO_RECRUITMENT_1" FOREIGN KEY ("GRADE_NO")
REFERENCES "GRADE" ("GRADE_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_WORKCOND_PERIOD_TO_RECRUITMENT_1" FOREIGN KEY ("PERIOD_NO")
REFERENCES "WORKCOND_PERIOD" ("PERIOD_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_WORKCOND_DAYS_TO_RECRUITMENT_1" FOREIGN KEY ("DAYS_NO")
REFERENCES "WORKCOND_DAYS" ("DAYS_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_WORKCOND_TIME_TO_RECRUITMENT_1" FOREIGN KEY ("TIME_NO")
REFERENCES "WORKCOND_TIME" ("TIME_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_EMPLOYER_TO_RECRUITMENT_1" FOREIGN KEY ("EMPLOYER_NO")
REFERENCES "EMPLOYER" ("EMPLOYER_NO");


ALTER TABLE "RECRUITMENT_SUPPORT" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_SUPPORT_1" FOREIGN KEY ("RECRUITMENT_NO")
REFERENCES "RECRUITMENT" ("RECRUITMENT_NO");


ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_PREFERRED_1" FOREIGN KEY ("RECRUITMENT_NO")
REFERENCES "RECRUITMENT" ("RECRUITMENT_NO");


ALTER TABLE "RECRUITMENT_IMG" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_IMG_1" FOREIGN KEY ("RECRUITMENT_NO")
REFERENCES "RECRUITMENT" ("RECRUITMENT_NO");


-- ALTER TABLE 테이블명 MODIFY 컬럼명 데이터타입; --> 데이터 타입 변경
ALTER TABLE "RECRUITMENT_SUPPORT" MODIFY SUPPORT_NO NVARCHAR2(10);
ALTER TABLE "RECRUITMENT_PREFERRED" MODIFY PREFERRED_NO NVARCHAR2(10);

-- 이거 안됨  -> 해결 완료
ALTER TABLE "RECRUITMENT_SUPPORT" ADD CONSTRAINT "FK_SUPPORT_TO_RECRUITMENT_SUPPORT_1" FOREIGN KEY ("SUPPORT_NO")
REFERENCES "SUPPORT" ("SUPPORT_NO");

-- 이거 안됨  -> 해결 완료
ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "FK_PREFERRED_TO_RECRUITMENT_PREFERRED_1" FOREIGN KEY ("PREFERRED_NO")
REFERENCES "PREFERRED" ("PREFERRED_NO");


---- 이하 데이터 삽입

----- GRADE (학력) --------------------------------------------
1, '무관'
2, '중졸'
3, '고졸'
4, '대졸(2,3년제)'
5, '대졸(4년제)'
6, '대학원 이상'


----- WORKCOND_PERIOD (근무기간) --------------------------------------------


----- WORKCOND_DAYS (근무요일) --------------------------------------------


----- WORKCOND_TIME (근무시간) --------------------------------------------