----- RECRUITMENT (채용공고) --------------------------------------------

CREATE TABLE "RECRUITMENT" (
	"RECRUITMENT_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_TITLE"	NVARCHAR2(100)		NOT NULL,
	"RECRUITMENT_CONTENT"	NVARCHAR2(2000)		NULL,
	"RECRUITMENT_DEADLINE"	DATE		NOT NULL,
	"WORKCOND_JOBTYPE"	NUMBER		NOT NULL,
	"NUM_OF_RECRUITMENT_NAME"	NVARCHAR2(20)		NOT NULL,
	"SALARY_NO"	NUMBER		NOT NULL,
	"GRADE_NO"	NUMBER		NOT NULL,
	"PERIOD_NO"	NUMBER		NOT NULL,
	"DAYS_NO"	NUMBER		NOT NULL,
	"TIME_NO"	NUMBER		NOT NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_NO" IS '공고번호(PK)';
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_TITLE" IS '채용공고 제목';
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_CONTENT" IS '채용공고 상세요강';
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_DEADLINE" IS 'ex) xxxx년xx월xx일';
COMMENT ON COLUMN "RECRUITMENT"."WORKCOND_JOBTYPE" IS '1(알바)/ 2(정규직)';
COMMENT ON COLUMN "RECRUITMENT"."NUM_OF_RECRUITMENT_NAME" IS '1(인원미정)/ 2(0명)/ 3(00명)';
COMMENT ON COLUMN "RECRUITMENT"."SALARY_NO" IS '급여조건 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."GRADE_NO" IS '학력번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."PERIOD_NO" IS '근무기간 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."DAYS_NO" IS '근무요일 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."TIME_NO" IS '근무시간 번호(FK)';
COMMENT ON COLUMN "RECRUITMENT"."EMPLOYER_NO" IS '고용주 번호(FK)';

----- RECRUITMENT_SUPPORT (채용공고_복리후생) --------------------------------------------

CREATE TABLE "RECRUITMENT_SUPPORT" (
	"RECRUITMENT_SUPPORT_NO"	NUMBER		NOT NULL,
	"SUPPORT_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_SUPPORT"."RECRUITMENT_SUPPORT_NO" IS 'M:N 해소(PK)';
COMMENT ON COLUMN "RECRUITMENT_SUPPORT"."SUPPORT_NO" IS '복리후생 번호 (FK)';
COMMENT ON COLUMN "RECRUITMENT_SUPPORT"."RECRUITMENT_NO" IS '공고번호(FK)';

----- RECRUITMENT_PREFERRED (채용공고_우대사항) --------------------------------------------

CREATE TABLE "RECRUITMENT_PREFERRED" (
	"RECRUITMENT_PREFERRED_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL,
	"PREFERRED_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."RECRUITMENT_PREFERRED_NO" IS 'M:N 해소(PK)';
COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."RECRUITMENT_NO" IS '공고번호(FK)';
COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."PREFERRED_NO" IS '우대사항 번호(FK)';

----- RECRUITMENT_IMG (공고 이미지) --------------------------------------------

CREATE TABLE "RECRUITMENT_IMG" (
	"RECRUITMENT_IMG_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_IMG_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"RECRUITMENT_IMG_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUITMENT_IMG_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUITMENT_IMG_IMG_ORDER"	NUMBER		NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_NO" IS '이미지 번호(PK)';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_PATH" IS '이미지 경로';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_ORIGINAL_NAME" IS '이미지 원본명';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_RENAME" IS '이미지 변경명';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_ORDER" IS '이미지 순서';
COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_NO" IS '공고번호(FK)';

----- GRADE (학력) --------------------------------------------

CREATE TABLE "GRADE" (
	"GRADE_NO"	NUMBER		NOT NULL,
	"GRADE_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_NO" IS '학력번호(PK)';
COMMENT ON COLUMN "GRADE"."GRADE_NAME" IS 'ex) 무관, 중졸, 고졸, 대졸, 석사 이상';

----- WORKCOND_PERIOD (근무기간) --------------------------------------------

CREATE TABLE "WORKCOND_PERIOD" (
	"PERIOD_NO"	NUMBER		NOT NULL,
	"PERIOD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_PERIOD"."PERIOD_NO" IS '근무기간 번호(PK)';
COMMENT ON COLUMN "WORKCOND_PERIOD"."PERIOD_NAME" IS 'ex) 하루, 1주일 이하, 1주일~1개월';

----- WORKCOND_DAYS (근무요일) --------------------------------------------

CREATE TABLE "WORKCOND_DAYS" (
	"DAYS_NO"	NUMBER		NOT NULL,
	"DATS_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_DAYS"."DAYS_NO" IS '근무요일 번호(PK)';
COMMENT ON COLUMN "WORKCOND_DAYS"."DATS_NAME" IS 'ex) 월~일, 월~토, 주말(토, 일), 주5일';

----- WORKCOND_TIME (근무시간) --------------------------------------------

CREATE TABLE "WORKCOND_TIME" (
	"TIME_NO"	NUMBER		NOT NULL,
	"TIME_NAME"	NVARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_TIME"."TIME_NO" IS '근무시간 번호(PK)';
COMMENT ON COLUMN "WORKCOND_TIME"."TIME_NAME" IS 'ex) 오전, 오후. 오전~오후, 새벽~오전';

----- RECRUITMENT_SALARY (급여) --------------------------------------------

CREATE TABLE "RECRUITMENT_SALARY" (
	"SALARY_NO"	NUMBER		NOT NULL,
	"SALARY_NAME"	NUMBER		NOT NULL,
	"SALARY_MOUNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_SALARY"."SALARY_NO" IS '급여조건 번호(PK)';
COMMENT ON COLUMN "RECRUITMENT_SALARY"."SALARY_NAME" IS '1(시급)/ 2(월급)/ 3(추후협의)';
COMMENT ON COLUMN "RECRUITMENT_SALARY"."SALARY_MOUNT" IS 'ex) 10,300(시급)/ 3,000,000(월급)';


COMMIT;


----- PK --------------------------------------------
ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "PK_RECRUITMENT_NO" PRIMARY KEY ("RECRUITMENT_NO");

ALTER TABLE "RECRUITMENT_SUPPORT" ADD CONSTRAINT "PK_RECRUITMENT_SUPPORT_NO" PRIMARY KEY ("RECRUITMENT_SUPPORT_NO");

ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "PK_RECRUITMENT_PREFERRED_NO" PRIMARY KEY ("RECRUITMENT_PREFERRED_NO");

ALTER TABLE "RECRUITMENT_IMG" ADD CONSTRAINT "PK_RECRUITMENT_IMG_NO" PRIMARY KEY ("RECRUITMENT_IMG_NO");

ALTER TABLE "GRADE" ADD CONSTRAINT "PK_GRADE_NO" PRIMARY KEY ("GRADE_NO");

ALTER TABLE "WORKCOND_PERIOD" ADD CONSTRAINT "PK_WORKCOND_PERIOD_NO" PRIMARY KEY ("PERIOD_NO");

ALTER TABLE "WORKCOND_DAYS" ADD CONSTRAINT "PK_WORKCOND_DAYS_NO" PRIMARY KEY ("DAYS_NO");

ALTER TABLE "WORKCOND_TIME" ADD CONSTRAINT "PK_WORKCOND_TIME_NO" PRIMARY KEY ("TIME_NO");

ALTER TABLE "RECRUITMENT_SALARY" ADD CONSTRAINT "PK_RECRUITMENT_SALARY_NO" PRIMARY KEY ("SALARY_NO");


----- FK --------------------------------------------

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_RECRUITMENT_SALARY_TO_RECRUITMENT_1" FOREIGN KEY ("SALARY_NO")
REFERENCES "RECRUITMENT_SALARY" ("SALARY_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_GRADE_TO_RECRUITMENT_1" FOREIGN KEY ("GRADE_NO")
REFERENCES "GRADE" ("GRADE_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_WORKCOND_PERIOD_TO_RECRUITMENT_1" FOREIGN KEY ("PERIOD_NO")
REFERENCES "WORKCOND_PERIOD" ("PERIOD_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_WORKCOND_DAYS_TO_RECRUITMENT_1" FOREIGN KEY ("DAYS_NO")
REFERENCES "WORKCOND_DAYS" ("DAYS_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_WORKCOND_TIME_TO_RECRUITMENT_1" FOREIGN KEY ("TIME_NO")
REFERENCES "WORKCOND_TIME" ("TIME_NO");

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_EMPLOYER_TO_RECRUITMENT_1" FOREIGN KEY ("EMPLOYER_NO")
REFERENCES "EMPLOYER" ("EMPLOYER_NO");


ALTER TABLE "RECRUITMENT_SUPPORT" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_SUPPORT_1" FOREIGN KEY ("RECRUITMENT_NO")
REFERENCES "RECRUITMENT" ("RECRUITMENT_NO");


ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_PREFERRED_1" FOREIGN KEY ("RECRUITMENT_NO")
REFERENCES "RECRUITMENT" ("RECRUITMENT_NO");


ALTER TABLE "RECRUITMENT_IMG" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_IMG_1" FOREIGN KEY ("RECRUITMENT_NO")
REFERENCES "RECRUITMENT" ("RECRUITMENT_NO");


-- ALTER TABLE 테이블명 MODIFY 컬럼명 데이터타입; --> 데이터 타입 변경
ALTER TABLE "RECRUITMENT_SUPPORT" MODIFY SUPPORT_NO NVARCHAR2(10);
ALTER TABLE "RECRUITMENT_PREFERRED" MODIFY PREFERRED_NO NVARCHAR2(10);

-- 이거 안됨  -> 해결 완료
ALTER TABLE "RECRUITMENT_SUPPORT" ADD CONSTRAINT "FK_SUPPORT_TO_RECRUITMENT_SUPPORT_1" FOREIGN KEY ("SUPPORT_NO")
REFERENCES "SUPPORT" ("SUPPORT_NO");

-- 이거 안됨  -> 해결 완료
ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "FK_PREFERRED_TO_RECRUITMENT_PREFERRED_1" FOREIGN KEY ("PREFERRED_NO")
REFERENCES "PREFERRED" ("PREFERRED_NO");


---- 이하 데이터 삽입

----- GRADE (학력) --------------------------------------------
1, '무관'
2, '중졸'
3, '고졸'
4, '대졸(2,3년제)'
5, '대졸(4년제)'
6, '대학원 이상'

INSERT INTO "GRADE" VALUES(1, '무관');
INSERT INTO "GRADE" VALUES(2, '중졸');
INSERT INTO "GRADE" VALUES(3, '고졸');
INSERT INTO "GRADE" VALUES(4, '대졸(2,3년제)');
INSERT INTO "GRADE" VALUES(5, '대졸(4년제)');
INSERT INTO "GRADE" VALUES(6, '대학원 이상');

SELECT * FROM GRADE;
COMMIT;

----- WORKCOND_PERIOD (근무기간) --------------------------------------------
1, '무관'
2, '하루'
3, '1주일이하'
4, '1주일~1개월'
5, '1개월~3개월'
6, '3개월~6개월'
7, '6개월~1년'
8, '1년 이상'

INSERT INTO "WORKCOND_PERIOD" VALUES(1, '무관');
INSERT INTO "WORKCOND_PERIOD" VALUES(2, '하루');
INSERT INTO "WORKCOND_PERIOD" VALUES(3, '1주일이하');
INSERT INTO "WORKCOND_PERIOD" VALUES(4, '1주일~1개월');
INSERT INTO "WORKCOND_PERIOD" VALUES(5, '1개월~3개월');
INSERT INTO "WORKCOND_PERIOD" VALUES(6, '3개월~6개월');
INSERT INTO "WORKCOND_PERIOD" VALUES(7, '6개월~1년');
INSERT INTO "WORKCOND_PERIOD" VALUES(8, '1년 이상');

SELECT * FROM WORKCOND_PERIOD;
COMMIT;

----- WORKCOND_DAYS (근무요일) --------------------------------------------
1, '무관'
2, '월~일'
3, '월~토'
4, '월~금'
5, '주말(토,일)'
6, '주6일'
7, '주5일'
8, '주4일'
9, '주3일'
10, '주2일'
11, '주1일'

INSERT INTO "WORKCOND_DAYS" VALUES(1, '무관');
INSERT INTO "WORKCOND_DAYS" VALUES(2, '월~일');
INSERT INTO "WORKCOND_DAYS" VALUES(3, '월~토');
INSERT INTO "WORKCOND_DAYS" VALUES(4, '월~금');
INSERT INTO "WORKCOND_DAYS" VALUES(5, '주말(토,일)');
INSERT INTO "WORKCOND_DAYS" VALUES(6, '주6일');
INSERT INTO "WORKCOND_DAYS" VALUES(7, '주5일');
INSERT INTO "WORKCOND_DAYS" VALUES(8, '주4일');
INSERT INTO "WORKCOND_DAYS" VALUES(9, '주3일');
INSERT INTO "WORKCOND_DAYS" VALUES(10, '주2일');
INSERT INTO "WORKCOND_DAYS" VALUES(11, '주1일');

SELECT * FROM WORKCOND_DAYS;
COMMIT;

----- WORKCOND_TIME (근무시간) --------------------------------------------
1, '무관'
2, '오전 파트타임(06시~12시)'
3, '오후 파트타임(12시~18시)'
4, '저녁 파트타임(18시~24시)'
5, '새벽 파트타임(00시~06시)'
6, '오전~오후 파트타임'
7, '오후~저녁 파트타임'
8, '저녁~새벽 파트타임'
9, '새벽~오전 파트타임'
10, '풀타임(8시간이상)'

INSERT INTO "WORKCOND_TIME" VALUES(1, '무관');
INSERT INTO "WORKCOND_TIME" VALUES(2, '오전 파트타임(06시~12시)');
INSERT INTO "WORKCOND_TIME" VALUES(3, '오후 파트타임(12시~18시)');
INSERT INTO "WORKCOND_TIME" VALUES(4, '저녁 파트타임(18시~24시)');
INSERT INTO "WORKCOND_TIME" VALUES(5, '새벽 파트타임(00시~06시)');
INSERT INTO "WORKCOND_TIME" VALUES(6, '오전~오후 파트타임');
INSERT INTO "WORKCOND_TIME" VALUES(7, '오후~저녁 파트타임');
INSERT INTO "WORKCOND_TIME" VALUES(8, '저녁~새벽 파트타임');
INSERT INTO "WORKCOND_TIME" VALUES(9, '새벽~오전 파트타임');
INSERT INTO "WORKCOND_TIME" VALUES(10, '풀타임(8시간이상)');

SELECT * FROM WORKCOND_TIME;
COMMIT;

ALTER TABLE RECRUITMENT ADD(RECRUITMENT_SALARY NUMBER);
SELECT * FROM RECRUITMENT;

ALTER TABLE RECRUITMENT DROP(RECRUITMENT_SALARY);

ALTER TABLE RECRUITMENT ADD(SALARY_MOUNT NUMBER);
COMMENT ON COLUMN "RECRUITMENT"."SALARY_MOUNT" IS 'ex) 10,300(시급)/ 3,000,000(월급)';
COMMIT;

ALTER TABLE RECRUITMENT_SALARY DROP(SALARY_MOUNT);

INSERT INTO "RECRUITMENT_SALARY" VALUES(1, '시급');
INSERT INTO "RECRUITMENT_SALARY" VALUES(2, '월급');
INSERT INTO "RECRUITMENT_SALARY" VALUES(3, '추후협의');

INSERT INTO "SALARY" VALUES(4, '추후협의(월급)');

UPDATE "SALARY"
SET SALARY_NAME = '추후협의(시급)'
WHERE SALARY_NO = 3;


SELECT * FROM SALARY;

COMMIT;

ALTER TABLE WORKCOND_DAYS RENAME COLUMN DATS_NAME TO DAYS_NAME;
SELECT * FROM WORKCOND_DAYS;


------241231 SQL문

SELECT SUBSTR(SUPPORT_NO, 1, 2) AS "supportNo", SUPPORT_CATEGORY AS "supportCategory"
FROM SUPPORT
WHERE SUPPORT_NO LIKE '__00';

CREATE SEQUENCE SEQ_RECRUITMENT_NO NOCACHE;

CREATE SEQUENCE SEQ_RECRUITMENT_SUPPORT_NO NOCACHE;
CREATE SEQUENCE SEQ_RECRUITMENT_PREFERRED_NO NOCACHE;

----- 250101 SQL 문
ALTER TABLE RECRUITMENT ADD(WRITE_DATE DATE DEFAULT SYSDATE);
COMMENT ON COLUMN "RECRUITMENT"."WRITE_DATE" IS '공고 등록날짜';

SELECT * FROM RECRUITMENT;

ALTER TABLE RECRUITMENT ADD(UPDATE_DATE DATE);
COMMENT ON COLUMN "RECRUITMENT"."UPDATE_DATE" IS '공고 수정날짜';

ALTER TABLE RECRUITMENT ADD(RECRUITMENT_DEL_FL CHAR(1) DEFAULT 'N');
COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_DEL_FL" IS '공고 삭제여부(Y/N)';

COMMIT;

SELECT COUNT(*)
FROM "RECRUITMENT" r 
WHERE RECRUITMENT_DEL_FL = 'N'
	AND EMPLOYER_NO = 4;

ALTER TABLE RECRUITMENT ADD(MEMBER_NO NUMBER);
COMMENT ON COLUMN "RECRUITMENT"."MEMBER_NO" IS '회원번호(FK)';


ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_RECRUITMENT_MEMBER_NO" FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

SELECT COUNT(*)
FROM "RECRUITMENT"
WHERE RECRUITMENT_DEL_FL = 'N'
	AND MEMBER_NO = 21;

SELECT RECRUITMENT_NO, RECRUITMENT_TITLE, e.BUSINESS_NICKNAME,
	CASE
		WHEN SYSDATE - WRITE_DATE < 1 / 24 / 60
		THEN FLOOR((SYSDATE - WRITE_DATE) * 24 * 60 * 60) || '초 전'
		
		WHEN SYSDATE - WRITE_DATE < 1 / 24
		THEN FLOOR((SYSDATE - WRITE_DATE) * 24 * 60) || '분 전'
		
		WHEN SYSDATE - WRITE_DATE < 1
		THEN FLOOR((SYSDATE - WRITE_DATE) * 24) || '시간 전'
		
		ELSE TO_CHAR(WRITE_DATE, 'YYYY-MM-DD') 
	END AS WRITE_DATE,
	TO_CHAR(RECRUITMENT_DEADLINE, 'YYYY/MM/DD') AS RECRUITMENT_DEADLINE
FROM RECRUITMENT r 
JOIN EMPLOYER e ON(r.EMPLOYER_NO = e.EMPLOYER_NO)
WHERE RECRUITMENT_DEL_FL = 'N'
	AND r.MEMBER_NO = 21
ORDER BY RECRUITMENT_NO DESC;


/* 공고 목록에서 띄울 사항
 * recruitmentNo, recruitmentTitle, businessName(join), 
 * businessAddress(join) 가운데(앞쪽에서 2개만 ex 서울 관악구),
 * salaryName(join), salaryMount, timeName(join)
 * writeDate, recruitmentDeadline
 * 
 * */

SELECT RECRUITMENT_NO, RECRUITMENT_TITLE, BUSINESS_NAME, BUSINESS_ADDRESS, SALARY_NAME, SALARY_MOUNT, TIME_NAME,
	CASE
		WHEN SYSDATE - WRITE_DATE < 1 / 24 / 60
		THEN FLOOR((SYSDATE - WRITE_DATE) * 24 * 60 * 60) || '초 전'
		
		WHEN SYSDATE - WRITE_DATE < 1 / 24
		THEN FLOOR((SYSDATE - WRITE_DATE) * 24 * 60) || '분 전'
		
		WHEN SYSDATE - WRITE_DATE < 1
		THEN FLOOR((SYSDATE - WRITE_DATE) * 24) || '시간 전'
		
		ELSE TO_CHAR(WRITE_DATE, 'YYYY-MM-DD') 
	END AS WRITE_DATE, 
	TO_CHAR(RECRUITMENT_DEADLINE, 'YYYY/MM/DD') AS RECRUITMENT_DEADLINE
FROM RECRUITMENT r 
JOIN EMPLOYER e ON (r.EMPLOYER_NO = e.EMPLOYER_NO)
JOIN SALARY s ON(r.SALARY_NO = s.SALARY_NO)
JOIN WORKCOND_TIME wt ON(r.TIME_NO = wt.TIME_NO)
WHERE RECRUITMENT_DEL_FL = 'N'
ORDER BY RECRUITMENT_NO DESC;

------ 250102 M:N 해소테이블 조회
SELECT RECRUITMENT_PREFERRED_NO, RECRUITMENT_NO, rp.PREFERRED_NO, p.PREFERRED_CATEGORY 
FROM RECRUITMENT_PREFERRED rp
JOIN PREFERRED p ON(rp.PREFERRED_NO = p.PREFERRED_NO)
WHERE RECRUITMENT_NO = 9
ORDER BY RECRUITMENT_PREFERRED_NO;

SELECT RECRUITMENT_SUPPORT_NO, RECRUITMENT_NO, rs.SUPPORT_NO, s.SUPPORT_CATEGORY 
FROM RECRUITMENT_SUPPORT rs
JOIN SUPPORT s ON(rs.SUPPORT_NO = s.SUPPORT_NO)
WHERE RECRUITMENT_NO = 9
ORDER BY RECRUITMENT_SUPPORT_NO;


------- 250102 일반 조회
SELECT *
FROM "RECRUITMENT"
WHERE RECRUITMENT_DEL_FL = 'N'
	AND RECRUITMENT_NO = 9;

SELECT BUSINESS_WORKTYPE_NO, EMPLOYER_NO, bw.WORKTYPE_NO, WORKTYPE_CATEGORY
FROM BUSINESS_WORKTYPE bw
JOIN EMPLOYER_WORKTYPE ew ON(bw.WORKTYPE_NO = ew.WORKTYPE_NO)
WHERE EMPLOYER_NO = 4;


SELECT RECRUITMENT_NO, RECRUITMENT_TITLE, RECRUITMENT_CONTENT, NUM_OF_RECRUITMENT_NAME,
	TO_CHAR(RECRUITMENT_DEADLINE, 'YYYY/MM/DD') AS RECRUITMENT_DEADLINE,
	TO_CHAR(WRITE_DATE, 'YYYY/MM/DD') AS WRITE_DATE,
	r.JOBTYPE_NO, j.JOBTYPE_NAME,
	r.SALARY_NO, s.SALARY_NAME, r.SALARY_MOUNT,
	r.GRADE_NO, g.GRADE_NAME,
	r.PERIOD_NO, wp.PERIOD_NAME,
	r.DAYS_NO, wd.DAYS_NAME,
	r.TIME_NO, wt.TIME_NAME,
	r.EMPLOYER_NO, e.BUSINESS_NICKNAME, e.BUSINESS_ADDRESS, e.BUSINESS_NAME 
FROM "RECRUITMENT" r
JOIN JOBTYPE j ON (r.JOBTYPE_NO = j.JOBTYPE_NO)
JOIN SALARY s ON(r.SALARY_NO = s.SALARY_NO)
JOIN GRADE g ON(r.GRADE_NO = g.GRADE_NO)
JOIN WORKCOND_PERIOD wp ON(r.PERIOD_NO = wp.PERIOD_NO)
JOIN WORKCOND_DAYS wd ON(r.DAYS_NO = wd.DAYS_NO)
JOIN WORKCOND_TIME wt ON(r.TIME_NO = wt.TIME_NO)
JOIN EMPLOYER e ON(r.EMPLOYER_NO = e.EMPLOYER_NO)
WHERE RECRUITMENT_DEL_FL = 'N'
	AND RECRUITMENT_NO = 9;