SELECT RESUME_TITLE,
	r.GRADE_NO, GRADE_NAME
	r.PERIOD_NO,
FROM "RESUME" r
JOIN GRADE g ON(r.GRADE_NO = g.GRADE_NO)
JOIN PERI
WHERE WORKER_NO = 9;

SELECT 
    R.RESUME_NO,
    R.RESUME_TITLE,             -- 필요한 경우 이력서 제목을 조회 (예시)
    J.JOBTYPE_NAME,             -- 직무 이름 (JOBTYPE 테이블에서)
    D.DAYS_NAME,                -- 근무 요일 이름 (WORKCOND_DAYS 테이블에서)
    T.TIME_NAME                 -- 근무 시간대 이름 (WORKCOND_TIME 테이블에서)
FROM RESUME R
JOIN RESUME_JOB_TYPE RJT ON R.RESUME_NO = RJT.RESUME_NO    -- RESUME과 RESUME_JOBTYPE을 JOIN
JOIN JOBTYPE J ON RJT.JOBTYPE_NO = J.JOBTYPE_NO           -- JOBTYPE과 RESUME_JOBTYPE을 JOIN
JOIN RESUME_DAYSTIME RDT ON R.RESUME_NO = RDT.RESUME_NO  -- RESUME과 RESUME_DAYSTIME을 JOIN
JOIN WORKCOND_DAYS D ON RDT.DAYS_NO = D.DAYS_NO           -- WORKCOND_DAYS와 RESUME_DAYSTIME을 JOIN
JOIN WORKCOND_TIME T ON RDT.TIME_NO = T.TIME_NO           -- WORKCOND_TIME와 RESUME_DAYSTIME을 JOIN
WHERE R.RESUME_DEL_FL = 'N'                                   -- 삭제되지 않은 이력서만 조회 (조건 예시)
	AND WORKER_NO = 31
ORDER BY R.RESUME_NO;                                           -- 결과 정렬 (선택사항)
