CREATE TABLE "RECRUITMENT" (
	"RECRUITMENT_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_TITLE"	NVARCHAR2(100)		NOT NULL,
	"RECRUITMENT_CONTENT"	NVARCHAR2(2000)		NULL,
	"RECRUITMENT_DEADLINE"	DATE		NOT NULL,
	"RECRUITMENT_NUMBER"	NVARCHAR2(100)		NOT NULL,
	"RECRUITMENT_GRADE"	NVARCHAR2(100)		NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_NO" IS '공고번호(PK)';

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_TITLE" IS '채용공고 제목';

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_CONTENT" IS '채용공고 상세요강';

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_DEADLINE" IS 'ex) xxxx년xx월xx일';

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_NUMBER" IS 'ex) 인원미정, 0명';

COMMENT ON COLUMN "RECRUITMENT"."RECRUITMENT_GRADE" IS 'ex) 학력무관';

COMMENT ON COLUMN "RECRUITMENT"."EMPLOYER_NO" IS '고용주 번호(FK)';

CREATE TABLE "WORKCOND" (
	"WORKCOND_NO"	NUMBER		NOT NULL,
	"WORKCOND_SALARY"	NUMBER		NOT NULL,
	"WORKCOND_PERIOD"	NVARCHAR2(100)		NOT NULL,
	"WORKCOND_DAYS"	NVARCHAR2(100)		NOT NULL,
	"WORKCOND_TIME"	NVARCHAR2(100)		NOT NULL,
	"WORKCOND_JOBTYPE"	NVARCHAR2(100)		NOT NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "WORKCOND"."WORKCOND_NO" IS '근무조건 번호(PK)';

COMMENT ON COLUMN "WORKCOND"."WORKCOND_SALARY" IS 'ex) 2,000,000원';

COMMENT ON COLUMN "WORKCOND"."WORKCOND_PERIOD" IS 'ex) 1년 이상';

COMMENT ON COLUMN "WORKCOND"."WORKCOND_DAYS" IS 'ex) 월~금';

COMMENT ON COLUMN "WORKCOND"."WORKCOND_TIME" IS 'ex) 일 8시간';

COMMENT ON COLUMN "WORKCOND"."WORKCOND_JOBTYPE" IS 'ex) 정규직';

COMMENT ON COLUMN "WORKCOND"."RECRUITMENT_NO" IS '공고번호(FK)';

CREATE TABLE "WORKCOND_WORKTYPE" (
	"WORKCOND_WORKTYPE_NO"	NUMBER		NOT NULL,
	"WORKCOND_NO"	NUMBER		NOT NULL,
	"WORKTYPE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_WORKTYPE"."WORKCOND_WORKTYPE_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "WORKCOND_WORKTYPE"."WORKCOND_NO" IS '근무조건 번호 (FK)';

COMMENT ON COLUMN "WORKCOND_WORKTYPE"."WORKTYPE_NO" IS '업직종 번호 (FK)';

CREATE TABLE "WORKTYPE" (
	"WORKTYPE_NO"	NUMBER		NOT NULL,
	"WORKTYPE_CATEGORY"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "WORKTYPE"."WORKTYPE_NO" IS '업직종 번호(PK)';

COMMENT ON COLUMN "WORKTYPE"."WORKTYPE_CATEGORY" IS 'ex) 사무직';

CREATE TABLE "WORKCOND_SUPPORT" (
	"WORKCOND_SUPPORT_NO"	NUMBER		NOT NULL,
	"WORKCOND_NO"	NUMBER		NOT NULL,
	"SUPPORT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "WORKCOND_SUPPORT"."WORKCOND_SUPPORT_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "WORKCOND_SUPPORT"."WORKCOND_NO" IS '근무조건 번호 (FK)';

COMMENT ON COLUMN "WORKCOND_SUPPORT"."SUPPORT_NO" IS '복리후생 번호 (FK)';

CREATE TABLE "SUPPORT" (
	"SUPPORT_NO"	NUMBER		NOT NULL,
	"SUPPORT_CATEGORY"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "SUPPORT"."SUPPORT_NO" IS '복리후생 번호(PK)';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_CATEGORY" IS 'ex) 국민연금,고용보험';

CREATE TABLE "RECRUITMENT_PREFERRED" (
	"RECRUITMENT_PREFERRED_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL,
	"PREFERRED_NO2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."RECRUITMENT_PREFERRED_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."RECRUITMENT_NO" IS '공고번호(FK)';

COMMENT ON COLUMN "RECRUITMENT_PREFERRED"."PREFERRED_NO2" IS '우대사항 번호(FK)';

CREATE TABLE "RECRUITMENT_IMG" (
	"RECRUITMENT_IMG_NO"	NUMBER		NOT NULL,
	"RECRUITMENT_IMG_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"RECRUITMENT_IMG_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUITMENT_IMG_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"RECRUITMENT_IMG_IMG_ORDER"	NUMBER		NULL,
	"RECRUITMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_NO" IS '이미지 번호(PK)';

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_PATH" IS '이미지 경로';

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_IMG_IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "RECRUITMENT_IMG"."RECRUITMENT_NO" IS '공고번호(FK)';

CREATE TABLE "MEMBERSHIP" (
	"MEMBERSHIP"	NUMBER		NOT NULL,
	"MEMBERSHIP_GRADE"	NUMBER		NOT NULL,
	"MEMBERSHIP_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBERSHIP_START_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBERSHIP_END_DATE"	DATE		NOT NULL,
	"MEMBERSHIP_EXPIRATION _DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBERSHIP_SUBSCRIPTION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP" IS '예시';

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP_GRADE" IS '1.골드 2실버 등';

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP_DEL_FL" IS '가입여부 확인';

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP_START_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP_END_DATE" IS '탈퇴일';

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP_EXPIRATION _DATE" IS '잔여일 기준점';

COMMENT ON COLUMN "MEMBERSHIP"."MEMBERSHIP_SUBSCRIPTION_FL" IS '구독 결제 여부';

COMMENT ON COLUMN "MEMBERSHIP"."EMPLOYER_NO" IS '고용주번호(FK)';

CREATE TABLE "PAYMENT" (
	"PAYMENT_NO"	NUMBER		NOT NULL,
	"PAYMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PAYMENT_AMOUNT"	NUMBER		NOT NULL,
	"PAYMENT_STATUS"	NVARCHAR2(20)		NOT NULL,
	"PAYMENT_BANK_TITLE"	NVARCHAR2(100)		NOT NULL,
	"PAYMENT_BANK_ACCOUNT"	NVARCHAR2(100)		NOT NULL,
	"MEMBERSHIP"	NUMBER		NOT NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAYMENT_NO" IS '예시';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_DATE" IS 'xxxx년 xx월 xx일 xx시 xx분';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_AMOUNT" IS '10000원';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_STATUS" IS '결제완료,결제실패 등 ( 내 결제내역 조회할때 필요)';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_BANK_TITLE" IS '매출을 관리하는 은행명';

COMMENT ON COLUMN "PAYMENT"."PAYMENT_BANK_ACCOUNT" IS '매출을 관리하는 은행계좌';

COMMENT ON COLUMN "PAYMENT"."MEMBERSHIP" IS '맴버쉽 번호(FK)';

COMMENT ON COLUMN "PAYMENT"."EMPLOYER_NO" IS '고용주번호(FK)';

CREATE TABLE "PAYMENT_TYPE" (
	"PAYMENT_TYPE"	NUMBER		NOT NULL,
	"PAYMENT_TYPE_FIRST"	NVARCHAR2(100)		NOT NULL,
	"PAYMENT_TYPE_SECOND"	NVARCHAR2(100)		NOT NULL,
	"PAYMENT_TYPE_FAV_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PAYMENT_TYPE_REFUND_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PAYMENT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PAYMENT_TYPE"."PAYMENT_TYPE" IS '예시';

COMMENT ON COLUMN "PAYMENT_TYPE"."PAYMENT_TYPE_FIRST" IS '은행,카드 등등 종류에 맞게 저장';

COMMENT ON COLUMN "PAYMENT_TYPE"."PAYMENT_TYPE_SECOND" IS '위 방법에 해당하는 계좌번호,카드번호 저장';

COMMENT ON COLUMN "PAYMENT_TYPE"."PAYMENT_TYPE_FAV_FL" IS '위 결제 수단을 즐찾';

COMMENT ON COLUMN "PAYMENT_TYPE"."PAYMENT_TYPE_REFUND_FL" IS '계좌이체 였을 경우 환불계좌로 등록 여부';

COMMENT ON COLUMN "PAYMENT_TYPE"."PAYMENT_NO" IS '결제번호(FK)';

CREATE TABLE "PREFERRED" (
	"PREFERRED_NO"	NUMBER		NOT NULL,
	"PREFERRED_CATEGORY"	NVARCHAR2(100)		NULL
);

COMMENT ON COLUMN "PREFERRED"."PREFERRED_NO" IS '우대사항 번호(PK)';

COMMENT ON COLUMN "PREFERRED"."PREFERRED_CATEGORY" IS 'ex) 유사업무 경험 우대, 인근 거주 우대';

CREATE TABLE "BUSINESS_WORKTYPE" (
	"BUSINESS_WORKTYPE_NO"	NUMBER		NOT NULL,
	"EMPLOYER_NO"	NUMBER		NOT NULL,
	"WORKTYPE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BUSINESS_WORKTYPE"."BUSINESS_WORKTYPE_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "BUSINESS_WORKTYPE"."EMPLOYER_NO" IS '고용주번호(FK)';

COMMENT ON COLUMN "BUSINESS_WORKTYPE"."WORKTYPE_NO" IS '업직종 번호(FK)';

CREATE TABLE "EMPLOYER_WORKTYPE" (
	"WORKTYPE_NO"	NUMBER		NOT NULL,
	"WORKTYPE_CATEGORY"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "EMPLOYER_WORKTYPE"."WORKTYPE_NO" IS '업직종 번호(PK)';

COMMENT ON COLUMN "EMPLOYER_WORKTYPE"."WORKTYPE_CATEGORY" IS 'ex) 사무직';


----- EMPLOYER TABLE 에서 M:N 해소테이블로 만든 컬럼 삭제
 ALTER TABLE "EMPLOYER" DROP COLUMN "BUSINESS_CATEGORY";
SELECT * FROM "EMPLOYER";
COMMIT;


------------------------ 이하 제약조건 ------------------------

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "PK_RECRUITMENT" PRIMARY KEY (
	"RECRUITMENT_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "EMPLOYER" ADD CONSTRAINT "PK_EMPLOYER" PRIMARY KEY (
	"EMPLOYER_NO"
);

ALTER TABLE "WORKCOND" ADD CONSTRAINT "PK_WORKCOND" PRIMARY KEY (
	"WORKCOND_NO"
);

ALTER TABLE "WORKCOND_WORKTYPE" ADD CONSTRAINT "PK_WORKCOND_WORKTYPE" PRIMARY KEY (
	"WORKCOND_WORKTYPE_NO"
);

ALTER TABLE "WORKTYPE" ADD CONSTRAINT "PK_WORKTYPE" PRIMARY KEY (
	"WORKTYPE_NO"
);

ALTER TABLE "WORKCOND_SUPPORT" ADD CONSTRAINT "PK_WORKCOND_SUPPORT" PRIMARY KEY (
	"WORKCOND_SUPPORT_NO"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "PK_SUPPORT" PRIMARY KEY (
	"SUPPORT_NO"
);

ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "PK_RECRUITMENT_PREFERRED" PRIMARY KEY (
	"RECRUITMENT_PREFERRED_NO"
);

ALTER TABLE "RECRUITMENT_IMG" ADD CONSTRAINT "PK_RECRUITMENT_IMG" PRIMARY KEY (
	"RECRUITMENT_IMG_NO"
);

ALTER TABLE "MEMBERSHIP" ADD CONSTRAINT "PK_MEMBERSHIP" PRIMARY KEY (
	"MEMBERSHIP"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_NO"
);

ALTER TABLE "PAYMENT_TYPE" ADD CONSTRAINT "PK_PAYMENT_TYPE" PRIMARY KEY (
	"PAYMENT_TYPE"
);

ALTER TABLE "PREFERRED" ADD CONSTRAINT "PK_PREFERRED" PRIMARY KEY (
	"PREFERRED_NO"
);

ALTER TABLE "BUSINESS_WORKTYPE" ADD CONSTRAINT "PK_BUSINESS_WORKTYPE" PRIMARY KEY (
	"BUSINESS_WORKTYPE_NO"
);

ALTER TABLE "EMPLOYER_WORKTYPE" ADD CONSTRAINT "PK_EMPLOYER_WORKTYPE" PRIMARY KEY (
	"WORKTYPE_NO"
);

ALTER TABLE "RECRUITMENT" ADD CONSTRAINT "FK_EMPLOYER_TO_RECRUITMENT_1" FOREIGN KEY (
	"EMPLOYER_NO"
)
REFERENCES "EMPLOYER" (
	"EMPLOYER_NO"
);

ALTER TABLE "EMPLOYER" ADD CONSTRAINT "FK_MEMBER_TO_EMPLOYER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "WORKCOND" ADD CONSTRAINT "FK_RECRUITMENT_TO_WORKCOND_1" FOREIGN KEY (
	"RECRUITMENT_NO"
)
REFERENCES "RECRUITMENT" (
	"RECRUITMENT_NO"
);

ALTER TABLE "WORKCOND_WORKTYPE" ADD CONSTRAINT "FK_WORKCOND_TO_WORKCOND_WORKTYPE_1" FOREIGN KEY (
	"WORKCOND_NO"
)
REFERENCES "WORKCOND" (
	"WORKCOND_NO"
);

ALTER TABLE "WORKCOND_WORKTYPE" ADD CONSTRAINT "FK_WORKTYPE_TO_WORKCOND_WORKTYPE_1" FOREIGN KEY (
	"WORKTYPE_NO"
)
REFERENCES "WORKTYPE" (
	"WORKTYPE_NO"
);

ALTER TABLE "WORKCOND_SUPPORT" ADD CONSTRAINT "FK_WORKCOND_TO_WORKCOND_SUPPORT_1" FOREIGN KEY (
	"WORKCOND_NO"
)
REFERENCES "WORKCOND" (
	"WORKCOND_NO"
);

ALTER TABLE "WORKCOND_SUPPORT" ADD CONSTRAINT "FK_SUPPORT_TO_WORKCOND_SUPPORT_1" FOREIGN KEY (
	"SUPPORT_NO"
)
REFERENCES "SUPPORT" (
	"SUPPORT_NO"
);

ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_PREFERRED_1" FOREIGN KEY (
	"RECRUITMENT_NO"
)
REFERENCES "RECRUITMENT" (
	"RECRUITMENT_NO"
);

ALTER TABLE "RECRUITMENT_PREFERRED" ADD CONSTRAINT "FK_PREFERRED_TO_RECRUITMENT_PREFERRED_1" FOREIGN KEY (
	"PREFERRED_NO2"
)
REFERENCES "PREFERRED" (
	"PREFERRED_NO"
);

ALTER TABLE "RECRUITMENT_IMG" ADD CONSTRAINT "FK_RECRUITMENT_TO_RECRUITMENT_IMG_1" FOREIGN KEY (
	"RECRUITMENT_NO"
)
REFERENCES "RECRUITMENT" (
	"RECRUITMENT_NO"
);

ALTER TABLE "MEMBERSHIP" ADD CONSTRAINT "FK_EMPLOYER_TO_MEMBERSHIP_1" FOREIGN KEY (
	"EMPLOYER_NO"
)
REFERENCES "EMPLOYER" (
	"EMPLOYER_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_MEMBERSHIP_TO_PAYMENT_1" FOREIGN KEY (
	"MEMBERSHIP"
)
REFERENCES "MEMBERSHIP" (
	"MEMBERSHIP"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_EMPLOYER_TO_PAYMENT_1" FOREIGN KEY (
	"EMPLOYER_NO"
)
REFERENCES "EMPLOYER" (
	"EMPLOYER_NO"
);

ALTER TABLE "PAYMENT_TYPE" ADD CONSTRAINT "FK_PAYMENT_TO_PAYMENT_TYPE_1" FOREIGN KEY (
	"PAYMENT_NO"
)
REFERENCES "PAYMENT" (
	"PAYMENT_NO"
);

ALTER TABLE "BUSINESS_WORKTYPE" ADD CONSTRAINT "FK_EMPLOYER_TO_BUSINESS_WORKTYPE_1" FOREIGN KEY (
	"EMPLOYER_NO"
)
REFERENCES "EMPLOYER" (
	"EMPLOYER_NO"
);

ALTER TABLE "BUSINESS_WORKTYPE" ADD CONSTRAINT "FK_EMPLOYER_WORKTYPE_TO_BUSINESS_WORKTYPE_1" FOREIGN KEY (
	"WORKTYPE_NO"
)
REFERENCES "EMPLOYER_WORKTYPE" (
	"WORKTYPE_NO"
);

-------- AUTHORITY FK 제약조건 TABLE
CREATE TABLE "AUTHORITY" (
	"AUTHORITY_NO" NUMBER PRIMARY KEY,
	"AUTHORITY_NAME" NVARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN "AUTHORITY"."AUTHORITY_NO" IS '권한 번호(PK)';
COMMENT ON COLUMN "AUTHORITY"."AUTHORITY_NAME" IS '권한 이름';

INSERT INTO "AUTHORITY" VALUES(1, '고용주');
INSERT INTO "AUTHORITY" VALUES(2, '알바생');
INSERT INTO "AUTHORITY" VALUES(3, '관리자');
INSERT INTO "AUTHORITY" VALUES(4, '상담원');

SELECT * FROM AUTHORITY;
COMMIT;

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_AUTHORITY" FOREIGN KEY ("AUTHORITY_NO")
REFERENCES "AUTHORITY" ("AUTHORITY_NO");

ALTER TABLE "MEMBER" RENAME COLUMN AUTHORITY TO AUTHORITY_NO;

COMMIT;


CREATE TABLE "MEMBERSHIP_LEVEL" (
	"MEMBERSHIP_NO" NUMBER PRIMARY KEY,
	"MEMBERSHIP_NAME" NVARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN "MEMBERSHIP_LEVEL"."MEMBERSHIP_NO" IS '멤버십 번호(PK)';
COMMENT ON COLUMN "MEMBERSHIP_LEVEL"."MEMBERSHIP_NAME" IS '멤버십 이름';

INSERT INTO "MEMBERSHIP_LEVEL" VALUES(1, 'BASIC');
INSERT INTO "MEMBERSHIP_LEVEL" VALUES(2, 'GOLD');
INSERT INTO "MEMBERSHIP_LEVEL" VALUES(3, 'PLATINUM');
INSERT INTO "MEMBERSHIP_LEVEL" VALUES(4, 'SHORT');
INSERT INTO "MEMBERSHIP_LEVEL" VALUES(5, 'HOT');

SELECT * FROM MEMBERSHIP_LEVEL;

COMMIT;

ALTER TABLE "EMPLOYER" ADD CONSTRAINT "FK_MEMBERSHIP_LEVEL" FOREIGN KEY ("MEMBERSHIP_LEVEL")
REFERENCES "MEMBERSHIP_LEVEL" ("MEMBERSHIP_NO");

ALTER TABLE "MEMBERSHIP" ADD CONSTRAINT "FK_MEMBERSHIP_TYPE" FOREIGN KEY ("MEMBERSHIP_TYPE")
REFERENCES "MEMBERSHIP_LEVEL" ("MEMBERSHIP_NO");

COMMIT;