CREATE TABLE "INQUIRY_ONE_ON_ONE" (
	"INQUIRY_NO"	NUMBER		NOT NULL,
	"INQUIRY_TYPE"	NVARCHAR2(10)		NOT NULL,
	"INQUIRY_TITLE"	NVARCHAR2(30)		NOT NULL,
	"INQUIRY_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"INQUIRY_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INQUIRY_STATUS"	NUMBER	DEFAULT 0	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."INQUIRY_NO" IS '문의글 번호(PK)';

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."INQUIRY_TYPE" IS '문의글 유형';

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."INQUIRY_TITLE" IS '문의글 제목';

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."INQUIRY_CONTENT" IS '문의글 내용';

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."INQUIRY_ENROLL_DATE" IS '문의글 작성일';

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."INQUIRY_STATUS" IS '0.안읽음 1. 읽음 2. 처리중 3. 처리완료 등등';

COMMENT ON COLUMN "INQUIRY_ONE_ON_ONE"."MEMBER_NO" IS '회원번호(FK)';

CREATE TABLE "INQUIRY_IMAGE" (
	"INQUIRY_IMAGE_NO"	NUMBER		NOT NULL,
	"INQUIRY_IMAGE_PATH"	VARCHAR2(200)		NOT NULL,
	"INQUIRY_IMAGE_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"INQUIRY_IMAGE_RENAME"	NVARCHAR2(50)		NOT NULL,
	"INQUIRY_IMAGE_ORDER"	NUMBER		NULL,
	"INQUIRY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "INQUIRY_IMAGE"."INQUIRY_IMAGE_NO" IS '이미지번호(PK)';

COMMENT ON COLUMN "INQUIRY_IMAGE"."INQUIRY_IMAGE_PATH" IS '이미지 요청경로';

COMMENT ON COLUMN "INQUIRY_IMAGE"."INQUIRY_IMAGE_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "INQUIRY_IMAGE"."INQUIRY_IMAGE_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "INQUIRY_IMAGE"."INQUIRY_IMAGE_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "INQUIRY_IMAGE"."INQUIRY_NO" IS '문의글 번호(FK)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(30)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"BOARD_READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시판번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시판제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시판내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시판글작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제여부(Y/N)';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "BOARD"."BOARD_CODE" IS '게시판 종류 코드번호(FK)';

CREATE TABLE "COMMENT_BOARD" (
	"COMMENT_NO_BOARD"	NUMBER		NOT NULL,
	"COMMENT_CONTENT_BOARD"	NVARCHAR2(500)		NOT NULL,
	"COMMENT_DEL_FL_BOARD"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"COMMENT_WRITE_DATE_BOARD"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "COMMENT_BOARD"."COMMENT_NO_BOARD" IS '댓글번호(PK)';

COMMENT ON COLUMN "COMMENT_BOARD"."COMMENT_CONTENT_BOARD" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT_BOARD"."COMMENT_DEL_FL_BOARD" IS '댓글 삭제여부(Y/N)';

COMMENT ON COLUMN "COMMENT_BOARD"."COMMENT_WRITE_DATE_BOARD" IS '댓글작성일';

COMMENT ON COLUMN "COMMENT_BOARD"."BOARD_NO" IS '게시판번호(FK)';

COMMENT ON COLUMN "COMMENT_BOARD"."MEMBER_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "COMMENT_BOARD"."PARENT_COMMENT_NO" IS '부모 댓글번호(FK)';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CODE" IS '게시판 종류 코드번호(PK)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS 'ex) 알바경험담, 한줄톡';

CREATE TABLE "BOARD_IMG" (
	"BOARD_IMG_NO"	NUMBER		NOT NULL,
	"BOARD_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"BOARD_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"BOARD_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"BOARD_IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_NO" IS '게시글 이미지번호(PK)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_PATH" IS '게시글 이미지 요청 경로';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORIGINAL_NAME" IS '게시글 이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_RENAME" IS '게시글 이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORDER" IS '게시글 이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시판번호(FK)';

CREATE TABLE "CHATTING_ROOM" (
	"CHATTING_ROOM_NO"	NUMBER		NOT NULL,
	"CREATE_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"CHATTING_ROOM_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"OPEN_MEMBER"	NUMBER		NOT NULL,
	"PARTICIPANT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CREATE_DATE" IS '채팅방 생성일';

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_ROOM_DEL_FL" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "CHATTING_ROOM"."OPEN_MEMBER" IS '개설자 회원 번호';

COMMENT ON COLUMN "CHATTING_ROOM"."PARTICIPANT" IS '참여자 회원 번호';

CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"MESSAGE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"READ_FL"	CHAR(1)		NOT NULL,
	"SEND_TIME"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"MACRO_FL"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"SENDER_NO"	NUMBER		NOT NULL,
	"CHATTING_ROOM_NO"	NUMBER		NOT NULL,
	"Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '메세지번호';

COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메세지 내용';

COMMENT ON COLUMN "MESSAGE"."READ_FL" IS '읽음여부Y/N';

COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '메시지 보낸 시간';

COMMENT ON COLUMN "MESSAGE"."MACRO_FL" IS '매크로여부Y/N';

COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '메세지 보낸 회원';

COMMENT ON COLUMN "MESSAGE"."CHATTING_ROOM_NO" IS '채팅방 번호';

CREATE TABLE "MESSAGE_MACRO" (
	"MESSAGE_MACRO_NO"	NUMBER		NOT NULL,
	"MESSAGE_MACRO_FIRST"	NUMBER		NOT NULL,
	"MESSAGE_MACRO_SECOND"	NUMBER		NOT NULL,
	"MESSAGE_MACRO_THIRD"	NUMBER		NOT NULL,
	"MESSAGE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MESSAGE_MACRO"."MESSAGE_MACRO_NO" IS '예시';

COMMENT ON COLUMN "MESSAGE_MACRO"."MESSAGE_MACRO_FIRST" IS '예제 질문의 최초 분류';

COMMENT ON COLUMN "MESSAGE_MACRO"."MESSAGE_MACRO_SECOND" IS '예제 질문의 두번째 분류';

COMMENT ON COLUMN "MESSAGE_MACRO"."MESSAGE_MACRO_THIRD" IS '예제 질문의 세번째 분류';

COMMENT ON COLUMN "MESSAGE_MACRO"."MESSAGE_NO" IS '메세지번호';



------------------------ 이하 제약조건 ------------------------

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "INQUIRY_ONE_ON_ONE" ADD CONSTRAINT "PK_INQUIRY_ONE_ON_ONE" PRIMARY KEY (
	"INQUIRY_NO"
);

ALTER TABLE "INQUIRY_IMAGE" ADD CONSTRAINT "PK_INQUIRY_IMAGE" PRIMARY KEY (
	"INQUIRY_IMAGE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "COMMENT_BOARD" ADD CONSTRAINT "PK_COMMENT_BOARD" PRIMARY KEY (
	"COMMENT_NO_BOARD"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CODE"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"BOARD_IMG_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
	"CHATTING_ROOM_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);

ALTER TABLE "MESSAGE_MACRO" ADD CONSTRAINT "PK_MESSAGE_MACRO" PRIMARY KEY (
	"MESSAGE_MACRO_NO"
);

ALTER TABLE "INQUIRY_ONE_ON_ONE" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_ONE_ON_ONE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "INQUIRY_IMAGE" ADD CONSTRAINT "FK_INQUIRY_ONE_ON_ONE_TO_INQUIRY_IMAGE_1" FOREIGN KEY (
	"INQUIRY_NO"
)
REFERENCES "INQUIRY_ONE_ON_ONE" (
	"INQUIRY_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CODE"
);

ALTER TABLE "COMMENT_BOARD" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_BOARD_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT_BOARD" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT_BOARD" ADD CONSTRAINT "FK_COMMENT_BOARD_TO_COMMENT_BOARD_1" FOREIGN KEY (
	"PARENT_COMMENT_NO"
)
REFERENCES "COMMENT_BOARD" (
	"COMMENT_NO_BOARD"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_1" FOREIGN KEY (
	"OPEN_MEMBER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_2" FOREIGN KEY (
	"PARTICIPANT"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_MEMBER_TO_MESSAGE_1" FOREIGN KEY (
	"SENDER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_MESSAGE_1" FOREIGN KEY (
	"CHATTING_ROOM_NO"
)
REFERENCES "CHATTING_ROOM" (
	"CHATTING_ROOM_NO"
);

ALTER TABLE "MESSAGE_MACRO" ADD CONSTRAINT "FK_MESSAGE_TO_MESSAGE_MACRO_1" FOREIGN KEY (
	"MESSAGE_NO"
)
REFERENCES "MESSAGE" (
	"MESSAGE_NO"
);

