CREATE TABLE "RESUME" (
	"RESUME_NO"	NUMBER		NOT NULL,
	"WORKER_GRADE"	NVARCHAR2(100)		NULL,
	"WORKER_CAREER"	NVARCHAR2(100)		NULL,
	"WORKER_INTRODUCE"	NVARCHAR2(1000)		NULL,
	"WORKER_OPENDATE"	DATE		NULL,
	"WORKER_OPEN_FL"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"WORKER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME"."RESUME_NO" IS '이력서번호(PK)';

COMMENT ON COLUMN "RESUME"."WORKER_GRADE" IS 'ex) 고졸, 대졸';

COMMENT ON COLUMN "RESUME"."WORKER_CAREER" IS '알바생경력';

COMMENT ON COLUMN "RESUME"."WORKER_INTRODUCE" IS '자기소개';

COMMENT ON COLUMN "RESUME"."WORKER_OPENDATE" IS '공개기간설정';

COMMENT ON COLUMN "RESUME"."WORKER_OPEN_FL" IS '공개여부확인 (Y/N)';

COMMENT ON COLUMN "RESUME"."WORKER_NO" IS '알바생번호(FK)';

CREATE TABLE "RESUME_CONDITION" (
	"HOPECOND_NO"	NUMBER		NOT NULL,
	"HOPECOND_SALARY"	NUMBER		NOT NULL,
	"HOPECOND_JOBTYPE"	NVARCHAR2(100)		NOT NULL,
	"RESUME_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CONDITION"."HOPECOND_NO" IS '근무조건 번호(PK)';

COMMENT ON COLUMN "RESUME_CONDITION"."HOPECOND_SALARY" IS 'ex) 2,000,000원';

COMMENT ON COLUMN "RESUME_CONDITION"."HOPECOND_JOBTYPE" IS 'ex) 정규직';

COMMENT ON COLUMN "RESUME_CONDITION"."RESUME_NO" IS '이력서번호(FK)';

CREATE TABLE "RESUME_CONDITION_WORKTYPE" (
	"COND_WORKTYPE_NO"	NUMBER		NOT NULL,
	"HOPECOND_NO"	NUMBER		NOT NULL,
	"HOPE_WORKTYPE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CONDITION_WORKTYPE"."COND_WORKTYPE_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "RESUME_CONDITION_WORKTYPE"."HOPECOND_NO" IS '근무조건 번호(FK)';

COMMENT ON COLUMN "RESUME_CONDITION_WORKTYPE"."HOPE_WORKTYPE_NO" IS '업직종 번호(FK)';

CREATE TABLE "RESUME_WORKTYPE" (
	"HOPE_WORKTYPE_NO"	NUMBER		NOT NULL,
	"HOPE_WORKTYPE_CATEGORY"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "RESUME_WORKTYPE"."HOPE_WORKTYPE_NO" IS '업직종 번호(PK)';

COMMENT ON COLUMN "RESUME_WORKTYPE"."HOPE_WORKTYPE_CATEGORY" IS 'ex) 사무직';

CREATE TABLE "RESUME_CONDITION_SUPPORT" (
	"COND_SUPPORT_NO"	NUMBER		NOT NULL,
	"HOPECOND_NO"	NUMBER		NOT NULL,
	"HOPE_SUPPORT_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CONDITION_SUPPORT"."COND_SUPPORT_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "RESUME_CONDITION_SUPPORT"."HOPECOND_NO" IS '근무조건 번호(FK)';

COMMENT ON COLUMN "RESUME_CONDITION_SUPPORT"."HOPE_SUPPORT_NO" IS '복리후생 번호(FK)';

CREATE TABLE "RESUME_SUPPORT" (
	"HOPE_SUPPORT_NO"	NUMBER		NOT NULL,
	"HOPE_SUPPORT_CATEGORY"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "RESUME_SUPPORT"."HOPE_SUPPORT_NO" IS '복리후생 번호(PK)';

COMMENT ON COLUMN "RESUME_SUPPORT"."HOPE_SUPPORT_CATEGORY" IS 'ex) 국민연금, 고용보험';

CREATE TABLE "RESUME_CONDITION_PERIOD" (
	"COND_PERIOD_NO"	NUMBER		NOT NULL,
	"HOPECOND_NO"	NUMBER		NOT NULL,
	"HOPE_PERIOD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CONDITION_PERIOD"."COND_PERIOD_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "RESUME_CONDITION_PERIOD"."HOPECOND_NO" IS '근무조건 번호(FK)';

COMMENT ON COLUMN "RESUME_CONDITION_PERIOD"."HOPE_PERIOD_NO" IS '근무기간 번호(FK)';

CREATE TABLE "RESUME_PERIOD" (
	"HOPE_PERIOD_NO"	NUMBER		NOT NULL,
	"HOPE_PERIOD_CATEGORY"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "RESUME_PERIOD"."HOPE_PERIOD_NO" IS '근무기간 번호(PK)';

COMMENT ON COLUMN "RESUME_PERIOD"."HOPE_PERIOD_CATEGORY" IS 'ex) 1주일 이하';

CREATE TABLE "RESUME_DAYS" (
	"HOPE_DAYS_NO"	NUMBER		NOT NULL,
	"HOPE_DAYS_CATEGORY"	NVARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "RESUME_DAYS"."HOPE_DAYS_NO" IS '근무요일 번호(PK)';

COMMENT ON COLUMN "RESUME_DAYS"."HOPE_DAYS_CATEGORY" IS 'ex) 월~일, 주6일';

CREATE TABLE "RESUME_TIME" (
	"HOPE_TIME_NO"	NUMBER		NOT NULL,
	"HOPE_TIME_CATEGORY"	NVARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "RESUME_TIME"."HOPE_TIME_NO" IS '근무시간 번호(PK)';

COMMENT ON COLUMN "RESUME_TIME"."HOPE_TIME_CATEGORY" IS 'ex) 오전 파트, 오전-오후파트';

CREATE TABLE "RESUME_CONDITION_DAYS" (
	"COND_DAYS_NO"	NUMBER		NOT NULL,
	"HOPECOND_NO"	NUMBER		NOT NULL,
	"HOPE_DAYS_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CONDITION_DAYS"."COND_DAYS_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "RESUME_CONDITION_DAYS"."HOPECOND_NO" IS '근무조건 번호(FK)';

COMMENT ON COLUMN "RESUME_CONDITION_DAYS"."HOPE_DAYS_NO" IS '근무요일 번호(FK)';

CREATE TABLE "RESUME_CONDITION_TIME" (
	"COND_TIME_NO"	NUMBER		NOT NULL,
	"HOPECOND_NO"	NUMBER		NOT NULL,
	"HOPE_TIME_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "RESUME_CONDITION_TIME"."COND_TIME_NO" IS 'M:N 해소(PK)';

COMMENT ON COLUMN "RESUME_CONDITION_TIME"."HOPECOND_NO" IS '근무조건 번호(FK)';

COMMENT ON COLUMN "RESUME_CONDITION_TIME"."HOPE_TIME_NO" IS '근무시간 번호(FK)';

CREATE TABLE "BLIND_BOARD" (
	"BLIND_BOARD_NO"	NUMBER		NOT NULL,
	"BLIND_BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BLIND_BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"BLIND_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BLIND_UPDATE_DATE"	DATE		NULL,
	"BLIND_BOARD_READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BLIND_BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"WORKER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_BOARD_NO" IS '블라인드 게시글 번호(PK)';

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_BOARD_TITLE" IS '블라인드 게시글 제목';

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_BOARD_CONTENT" IS '블라인드 게시글 내용';

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_WRITE_DATE" IS '블라인드 게시글 작성일';

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_UPDATE_DATE" IS '마지막 수정일';

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_BOARD_READ_COUNT" IS '조회 수';

COMMENT ON COLUMN "BLIND_BOARD"."BLIND_BOARD_DEL_FL" IS '삭제여부(Y/N)';

COMMENT ON COLUMN "BLIND_BOARD"."WORKER_NO" IS '알바생번호(FK)';

CREATE TABLE "COMMENT_BLIND_BOARD" (
	"BLIND_COMMENT_NO"	NUMBER		NOT NULL,
	"BLIND_COMMENT_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"BLIND_COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BLIND_COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BLIND_BOARD_NO"	NUMBER		NOT NULL,
	"BLIND_COMMENT_NO2"	NUMBER		NOT NULL,
	"WORKER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."BLIND_COMMENT_NO" IS '블라인드 게시판 댓글번호(PK)';

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."BLIND_COMMENT_CONTENT" IS '블라인드 게시판 댓글 내용';

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."BLIND_COMMENT_DEL_FL" IS '댓글 삭제여부(Y/N)';

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."BLIND_COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."BLIND_BOARD_NO" IS '블라인드 게시글 번호(FK)';

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."BLIND_COMMENT_NO2" IS '블라인드 게시판 댓글번호(FK)';

COMMENT ON COLUMN "COMMENT_BLIND_BOARD"."WORKER_NO" IS '알바생번호(FK)';



------------------------ 이하 제약조건 ------------------------

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "WORKER" ADD CONSTRAINT "PK_WORKER" PRIMARY KEY (
	"WORKER_NO"
);

ALTER TABLE "INQUIRY_ONE_ON_ONE" ADD CONSTRAINT "PK_INQUIRY_ONE_ON_ONE" PRIMARY KEY (
	"INQUIRY_NO"
);

ALTER TABLE "INQUIRY_IMAGE" ADD CONSTRAINT "PK_INQUIRY_IMAGE" PRIMARY KEY (
	"INQUIRY_IMAGE_NO"
);

ALTER TABLE "RESUME" ADD CONSTRAINT "PK_RESUME" PRIMARY KEY (
	"RESUME_NO"
);

ALTER TABLE "RESUME_CONDITION" ADD CONSTRAINT "PK_RESUME_CONDITION" PRIMARY KEY (
	"HOPECOND_NO"
);

ALTER TABLE "RESUME_CONDITION_WORKTYPE" ADD CONSTRAINT "PK_RESUME_CONDITION_WORKTYPE" PRIMARY KEY (
	"COND_WORKTYPE_NO"
);

ALTER TABLE "RESUME_WORKTYPE" ADD CONSTRAINT "PK_RESUME_WORKTYPE" PRIMARY KEY (
	"HOPE_WORKTYPE_NO"
);

ALTER TABLE "RESUME_CONDITION_SUPPORT" ADD CONSTRAINT "PK_RESUME_CONDITION_SUPPORT" PRIMARY KEY (
	"COND_SUPPORT_NO"
);

ALTER TABLE "RESUME_SUPPORT" ADD CONSTRAINT "PK_RESUME_SUPPORT" PRIMARY KEY (
	"HOPE_SUPPORT_NO"
);

ALTER TABLE "RESUME_CONDITION_PERIOD" ADD CONSTRAINT "PK_RESUME_CONDITION_PERIOD" PRIMARY KEY (
	"COND_PERIOD_NO"
);

ALTER TABLE "RESUME_PERIOD" ADD CONSTRAINT "PK_RESUME_PERIOD" PRIMARY KEY (
	"HOPE_PERIOD_NO"
);

ALTER TABLE "RESUME_DAYS" ADD CONSTRAINT "PK_RESUME_DAYS" PRIMARY KEY (
	"HOPE_DAYS_NO"
);

ALTER TABLE "RESUME_TIME" ADD CONSTRAINT "PK_RESUME_TIME" PRIMARY KEY (
	"HOPE_TIME_NO"
);

ALTER TABLE "RESUME_CONDITION_DAYS" ADD CONSTRAINT "PK_RESUME_CONDITION_DAYS" PRIMARY KEY (
	"COND_DAYS_NO"
);

ALTER TABLE "RESUME_CONDITION_TIME" ADD CONSTRAINT "PK_RESUME_CONDITION_TIME" PRIMARY KEY (
	"COND_TIME_NO"
);

ALTER TABLE "BLIND_BOARD" ADD CONSTRAINT "PK_BLIND_BOARD" PRIMARY KEY (
	"BLIND_BOARD_NO"
);

ALTER TABLE "COMMENT_BLIND_BOARD" ADD CONSTRAINT "PK_COMMENT_BLIND_BOARD" PRIMARY KEY (
	"BLIND_COMMENT_NO"
);

ALTER TABLE "WORKER" ADD CONSTRAINT "FK_MEMBER_TO_WORKER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "INQUIRY_ONE_ON_ONE" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_ONE_ON_ONE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "INQUIRY_IMAGE" ADD CONSTRAINT "FK_INQUIRY_ONE_ON_ONE_TO_INQUIRY_IMAGE_1" FOREIGN KEY (
	"INQUIRY_NO"
)
REFERENCES "INQUIRY_ONE_ON_ONE" (
	"INQUIRY_NO"
);

ALTER TABLE "RESUME" ADD CONSTRAINT "FK_WORKER_TO_RESUME_1" FOREIGN KEY (
	"WORKER_NO"
)
REFERENCES "WORKER" (
	"WORKER_NO"
);

ALTER TABLE "RESUME_CONDITION" ADD CONSTRAINT "FK_RESUME_TO_RESUME_CONDITION_1" FOREIGN KEY (
	"RESUME_NO"
)
REFERENCES "RESUME" (
	"RESUME_NO"
);

ALTER TABLE "RESUME_CONDITION_WORKTYPE" ADD CONSTRAINT "FK_RESUME_CONDITION_TO_RESUME_CONDITION_WORKTYPE_1" FOREIGN KEY (
	"HOPECOND_NO"
)
REFERENCES "RESUME_CONDITION" (
	"HOPECOND_NO"
);

ALTER TABLE "RESUME_CONDITION_WORKTYPE" ADD CONSTRAINT "FK_RESUME_WORKTYPE_TO_RESUME_CONDITION_WORKTYPE_1" FOREIGN KEY (
	"HOPE_WORKTYPE_NO"
)
REFERENCES "RESUME_WORKTYPE" (
	"HOPE_WORKTYPE_NO"
);

ALTER TABLE "RESUME_CONDITION_SUPPORT" ADD CONSTRAINT "FK_RESUME_CONDITION_TO_RESUME_CONDITION_SUPPORT_1" FOREIGN KEY (
	"HOPECOND_NO"
)
REFERENCES "RESUME_CONDITION" (
	"HOPECOND_NO"
);

ALTER TABLE "RESUME_CONDITION_SUPPORT" ADD CONSTRAINT "FK_RESUME_SUPPORT_TO_RESUME_CONDITION_SUPPORT_1" FOREIGN KEY (
	"HOPE_SUPPORT_NO"
)
REFERENCES "RESUME_SUPPORT" (
	"HOPE_SUPPORT_NO"
);

ALTER TABLE "RESUME_CONDITION_PERIOD" ADD CONSTRAINT "FK_RESUME_CONDITION_TO_RESUME_CONDITION_PERIOD_1" FOREIGN KEY (
	"HOPECOND_NO"
)
REFERENCES "RESUME_CONDITION" (
	"HOPECOND_NO"
);

ALTER TABLE "RESUME_CONDITION_PERIOD" ADD CONSTRAINT "FK_RESUME_PERIOD_TO_RESUME_CONDITION_PERIOD_1" FOREIGN KEY (
	"HOPE_PERIOD_NO"
)
REFERENCES "RESUME_PERIOD" (
	"HOPE_PERIOD_NO"
);

ALTER TABLE "RESUME_CONDITION_DAYS" ADD CONSTRAINT "FK_RESUME_CONDITION_TO_RESUME_CONDITION_DAYS_1" FOREIGN KEY (
	"HOPECOND_NO"
)
REFERENCES "RESUME_CONDITION" (
	"HOPECOND_NO"
);

ALTER TABLE "RESUME_CONDITION_DAYS" ADD CONSTRAINT "FK_RESUME_DAYS_TO_RESUME_CONDITION_DAYS_1" FOREIGN KEY (
	"HOPE_DAYS_NO"
)
REFERENCES "RESUME_DAYS" (
	"HOPE_DAYS_NO"
);

ALTER TABLE "RESUME_CONDITION_TIME" ADD CONSTRAINT "FK_RESUME_CONDITION_TO_RESUME_CONDITION_TIME_1" FOREIGN KEY (
	"HOPECOND_NO"
)
REFERENCES "RESUME_CONDITION" (
	"HOPECOND_NO"
);

ALTER TABLE "RESUME_CONDITION_TIME" ADD CONSTRAINT "FK_RESUME_TIME_TO_RESUME_CONDITION_TIME_1" FOREIGN KEY (
	"HOPE_TIME_NO"
)
REFERENCES "RESUME_TIME" (
	"HOPE_TIME_NO"
);

ALTER TABLE "BLIND_BOARD" ADD CONSTRAINT "FK_WORKER_TO_BLIND_BOARD_1" FOREIGN KEY (
	"WORKER_NO"
)
REFERENCES "WORKER" (
	"WORKER_NO"
);

ALTER TABLE "COMMENT_BLIND_BOARD" ADD CONSTRAINT "FK_BLIND_BOARD_TO_COMMENT_BLIND_BOARD_1" FOREIGN KEY (
	"BLIND_BOARD_NO"
)
REFERENCES "BLIND_BOARD" (
	"BLIND_BOARD_NO"
);

ALTER TABLE "COMMENT_BLIND_BOARD" ADD CONSTRAINT "FK_COMMENT_BLIND_BOARD_TO_COMMENT_BLIND_BOARD_1" FOREIGN KEY (
	"BLIND_COMMENT_NO2"
)
REFERENCES "COMMENT_BLIND_BOARD" (
	"BLIND_COMMENT_NO"
);

ALTER TABLE "COMMENT_BLIND_BOARD" ADD CONSTRAINT "FK_WORKER_TO_COMMENT_BLIND_BOARD_1" FOREIGN KEY (
	"WORKER_NO"
)
REFERENCES "WORKER" (
	"WORKER_NO"
);

