CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원이름/사업주명';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호(비번찾기용)';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1:고용주, 2:알바생, 3:관리자)';

CREATE TABLE "EMPLOYER" (
	"EMPLOYER_NO"	NUMBER		NOT NULL,
	"BUSINESS_REGISTRATION_NUMBER"	NVARCHAR2(40)		NOT NULL,
	"BUSINESS_NAME"	NVARCHAR2(300)		NOT NULL,
	"BUSINESS_ADDRESS"	NVARCHAR2(300)		NOT NULL,
	"BUSINESS_IMG"	VARCHAR2(300)		NULL,
	"BUSINESS_CATEGORY"	NVARCHAR2(20)		NOT NULL,
	"MEMBERSHIP_LEVEL"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EMPLOYER"."EMPLOYER_NO" IS '고용주번호(PK)';

COMMENT ON COLUMN "EMPLOYER"."BUSINESS_REGISTRATION_NUMBER" IS '사업자 등록번호';

COMMENT ON COLUMN "EMPLOYER"."BUSINESS_NAME" IS '사업장 이름';

COMMENT ON COLUMN "EMPLOYER"."BUSINESS_ADDRESS" IS '사업장 주소';

COMMENT ON COLUMN "EMPLOYER"."BUSINESS_IMG" IS '사업장 대표 이미지(회사로고)';

COMMENT ON COLUMN "EMPLOYER"."BUSINESS_CATEGORY" IS '사업장 카테고리(업종)';

COMMENT ON COLUMN "EMPLOYER"."MEMBERSHIP_LEVEL" IS '등급(1: 기본, 2:실버, 3:골드, 4:플레티넘)';

COMMENT ON COLUMN "EMPLOYER"."MEMBER_NO" IS '회원번호(FK)';

CREATE TABLE "WORKER" (
	"WORKER_NO"	NUMBER		NOT NULL,
	"WORKER_ID"	NVARCHAR2(20)		NOT NULL,
	"WORKER_NICKNAME"	NVARCHAR2(20)		NOT NULL,
	"WORKER_BIRTHDATE"	DATE		NOT NULL,
	"WORKER_ADDRESS"	NVARCHAR2(300)		NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"SIGN_UP_PATH"	NUMBER		NULL,
	"FAST_LOGIN_TOKEN"	NVARCHAR2(300)		NULL,
	"BLIND_LOGIN_ID"	NVARCHAR2(30)		NULL,
	"WORKER_MBTI"	VARCHAR2(4)		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "WORKER"."WORKER_NO" IS '알바생번호(PK)';

COMMENT ON COLUMN "WORKER"."WORKER_ID" IS '알바생 아이디(로그인용)';

COMMENT ON COLUMN "WORKER"."WORKER_NICKNAME" IS '알바생 닉네임(게시글용)';

COMMENT ON COLUMN "WORKER"."WORKER_BIRTHDATE" IS '알바생 생년월일';

COMMENT ON COLUMN "WORKER"."WORKER_ADDRESS" IS '알바생 주소';

COMMENT ON COLUMN "WORKER"."PROFILE_IMG" IS '프로필이미지(마이페이지)';

COMMENT ON COLUMN "WORKER"."SIGN_UP_PATH" IS '가입경로(1, 2, 3, 4, 5, 6)';

COMMENT ON COLUMN "WORKER"."FAST_LOGIN_TOKEN" IS '빠른로그인(카카오톡 토큰)';

COMMENT ON COLUMN "WORKER"."BLIND_LOGIN_ID" IS '블라인드 게시판 이용할 경우';

COMMENT ON COLUMN "WORKER"."WORKER_MBTI" IS 'MBTI(마이페이지 저장용)';

COMMENT ON COLUMN "WORKER"."MEMBER_NO" IS '회원번호(FK)';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "EMPLOYER" ADD CONSTRAINT "PK_EMPLOYER" PRIMARY KEY (
	"EMPLOYER_NO"
);

ALTER TABLE "WORKER" ADD CONSTRAINT "PK_WORKER" PRIMARY KEY (
	"WORKER_NO"
);

ALTER TABLE "EMPLOYER" ADD CONSTRAINT "FK_MEMBER_TO_EMPLOYER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "WORKER" ADD CONSTRAINT "FK_MEMBER_TO_WORKER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


BEGIN
		INSERT INTO "MEMBER"
		VALUES(SEQ_MEMBER_NO.NEXTVAL, 
			'123',
			123,
			'123',
			123,						 
			 DEFAULT,
			 DEFAULT,
			 2
			 );
		INSERT INTO "WORKER"
		VALUES(SEQ_WORKER_NO.NEXTVAL,
			'123',
			'123',
			DEFAULT,
			'123',
			'123',
			123,
			'123',
			'123',
			'123',
			17
		);		
	 END;

SELECT 	(SEQ_MEMBER_NO.NEXTVAL - 1 ) FROM DUAL;
COMMIT;
ROLLBACK;

