spring.application.name=finalproject-admin-server

# admin 계정은 포트 번호 8080으로 유지(클라이언트와 같이 켜질때를 대비)

#Spring devTools 관련 설정
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false

#로깅 레벨 지정
# (trace < debug < info < warn < error < fatal )
logging.level.edu.kh.project=debug

#URL에 jsessionId가 보여질 때 jsessionId를 쿠키에 담으라는 설정
server.servlet.session.tracking-modes=cookie